#!/usr/bin/env python3
"""One-time transform: build src/data.js from the v4 lab snapshot + prestige elevations.
Applies known results through 12 June 2026. Re-runnable."""
import json, re, pathlib

DL = pathlib.Path.home() / "Downloads"
HERE = pathlib.Path(__file__).parent
v4 = json.load(open(DL / "worldcup_forecast_lab_v4_no_terminal_package/worldcup2026-data-v4.json"))

# Elevations from prestige data.js, keyed by city
prestige = open(DL / "prestige-analytics-world-cup-2026/data.js").read()
elevs = {}
for m in re.finditer(r'\{[^{}]*city:\s*"([^"]+)"[^{}]*elev:\s*(\d+)[^{}]*\}', prestige):
    elevs[m.group(1)] = int(m.group(2))

teams = []
for t in v4["teams"]:
    teams.append({
        "code": t["code"], "name": t["name"], "flag": t["flag"], "group": t["group"],
        "fifaRank": t["fifaRank"], "confed": t["confederation"], "baseRating": t["rating"],
        # pre-tournament external blend (11 June snapshot), kept for the Model panel comparison only
        "preProb": t.get("titleProb"), "marketProb": t.get("marketProb"),
    })

venues = []
for v in v4["venues"]:
    venues.append({
        "id": v["id"], "name": v["stadium"], "fifaName": v["fifaName"], "city": v["city"],
        "country": v["country"], "capacity": v["capacity"], "lat": v["lat"], "lon": v["lon"],
        "elev": elevs.get(v["city"], 0),
    })

matches = []
for m in v4["matches"]:
    matches.append({
        "id": m["id"], "stage": "group", "group": m["group"], "dateET": m["dateET"],
        "team1": m["team1"], "team2": m["team2"], "venueId": m["venueId"],
        "status": m["status"], "score": m["score"],
    })

# Known results through the morning of 12 June 2026 (Kuwait)
RESULTS = {
    "M001": (2, 0),  # Mexico 2-0 South Africa, 11 Jun (already in snapshot)
    "M002": (2, 1),  # South Korea 2-1 Czechia, 11 Jun (Sky/ESPN/NBC, fetched 12 Jun)
}
for m in matches:
    if m["id"] in RESULTS:
        s = RESULTS[m["id"]]
        m["status"] = "completed"
        m["score"] = {"team1": s[0], "team2": s[1]}

# sanity: M002 is KOR vs CZE
m2 = next(m for m in matches if m["id"] == "M002")
assert (m2["team1"], m2["team2"]) == ("KOR", "CZE"), f"M002 is {m2['team1']} vs {m2['team2']}"

# MENA contingent (Arab League members + Iran present in the 48)
MENA_CODES = ["MAR", "EGY", "ALG", "TUN", "KSA", "QAT", "JOR", "IRN", "IRQ", "UAE", "LBN", "OMA", "KUW"]
mena = [t["code"] for t in teams if t["code"] in MENA_CODES]

data = {
    "meta": {
        "title": "World Cup 2026 — Probability Centre",
        "version": "1.0",
        "asOf": "2026-06-12",
        "asOfNote": "Results through matchday 1 (11 June 2026). Probabilities recompute in your browser from this data.",
        "sources": [
            {"name": "FIFA fixtures and standings", "url": "https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026/scores-fixtures"},
            {"name": "Base ratings: Elo-style ratings derived from FIFA rankings (11 June 2026 snapshot)", "url": "https://www.fifa.com/en/ranking/men"},
        ],
    },
    "teams": teams,
    "venues": venues,
    "matches": matches,
    "r32Template": v4["round32Template"],
    "koSchedule": v4["knockoutSchedule"],
    "mena": mena,
    "watchlist": [
        {"player": "Cole Palmer", "team": "ENG", "note": "Chelsea"},
    ],
    "league": {"entries": [], "scoring": {"groupWinner": 2, "finalist": 4, "champion": 10}},
}

hist_path = HERE / "src" / "history.json"
if not hist_path.exists():
    # Seed the timeline with the pre-tournament external-blend snapshot (labelled as such)
    pre = {t["code"]: t["preProb"] for t in teams if t.get("preProb")}
    json.dump([{"date": "2026-06-11", "label": "Pre-tournament (external blend)", "probs": pre}],
              open(hist_path, "w"), indent=1)

out = "// Generated by transform.py — do not edit by hand. Patch results here, then rebuild.\n"
out += "const WC_DATA = " + json.dumps(data, ensure_ascii=False, indent=1) + ";\n"
out += "if (typeof module !== 'undefined') module.exports = { WC_DATA };\n"
(HERE / "src" / "data.js").write_text(out)
print(f"teams={len(teams)} matches={len(matches)} venues={len(venues)} mena={mena}")
print(f"r32 slots={len(data['r32Template'])}")
print("slot types:", sorted({(s['a']['type'], s['b']['type']) for s in data['r32Template']}))
