#!/usr/bin/env python3
"""Pull completed match scores from ESPN's open JSON feed and patch src/data.js.
Used by the GitHub Actions auto-update workflow and runnable locally. Stdlib only.

Safety rails: only matches already in the fixture list, only STATUS_FULL_TIME,
only sane integer scores, never touches the model or anything but scores/asOf.
Exits 0 always; writes "changed=true|false" to $GITHUB_OUTPUT when set.
"""
import json, os, re, sys, datetime, urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, 'src', 'data.js')
MAP = os.path.join(ROOT, 'src', 'espn-map.json')
TOURNAMENT_END = datetime.date(2026, 7, 20)
LOOKBACK_HOURS = 36
FEED = "https://site.api.espn.com/apis/site/v2/sports/soccer/fifa.world/scoreboard?dates={d}"

def out(changed, msg):
    print(msg)
    gh = os.environ.get('GITHUB_OUTPUT')
    if gh:
        with open(gh, 'a') as f:
            f.write(f"changed={'true' if changed else 'false'}\n")
    sys.exit(0)

now = datetime.datetime.now(datetime.timezone.utc)
if now.date() > TOURNAMENT_END:
    out(False, f"Past tournament end ({TOURNAMENT_END}); nothing to do.")

raw = open(DATA).read()
m0 = re.search(r'const WC_DATA = (\{.*?\});\nif \(typeof module', raw, re.S)
if not m0:
    out(False, "Could not parse WC_DATA from src/data.js (shape changed?); leaving untouched.")
data = json.loads(m0.group(1))
idmap = json.load(open(MAP))['teamIds']

# pending: not completed, kicked off within the lookback window
pending = []
for m in data['matches']:
    if m['status'] == 'completed':
        continue
    ko = datetime.datetime.fromisoformat(m['dateET'])
    if ko.tzinfo is None:
        ko = ko.replace(tzinfo=datetime.timezone(datetime.timedelta(hours=-4)))
    if datetime.timedelta(0) <= now - ko <= datetime.timedelta(hours=LOOKBACK_HOURS):
        pending.append(m)
if not pending:
    out(False, "No pending matches in the lookback window; feed not fetched.")

# ESPN buckets the dates param by US Eastern; dateET already carries the Eastern date
dates = sorted({m['dateET'][:10].replace('-', '') for m in pending})
rng = dates[0] if len(dates) == 1 else f"{dates[0]}-{dates[-1]}"
try:
    req = urllib.request.Request(FEED.format(d=rng), headers={'User-Agent': 'worldcup-2026-auto-update'})
    evs = json.load(urllib.request.urlopen(req, timeout=30)).get('events', [])
except Exception as e:
    out(False, f"Feed unreachable ({e}); leaving data untouched.")

bypair = {frozenset([m['team1'], m['team2']]): m for m in pending}
applied = []
for e in evs:
    try:
        st = e['status']['type']
        if st['name'] != 'STATUS_FULL_TIME' or not st.get('completed'):
            continue
        comp = e['competitions'][0]
        scores, shootout_winner = {}, None
        for c in comp['competitors']:
            code = idmap.get(str(c['team']['id'])) or c['team'].get('abbreviation')
            scores[code] = int(c['score'])
            if c.get('winner'):
                shootout_winner = code
        match = bypair.get(frozenset(scores.keys()))
        if not match:
            continue
        s1, s2 = scores[match['team1']], scores[match['team2']]
        if not (0 <= s1 <= 15 and 0 <= s2 <= 15):
            print(f"Rejected implausible score {s1}-{s2} for {match['id']}")
            continue
        match['status'] = 'completed'
        match['score'] = {'team1': s1, 'team2': s2}
        # knockout draw decided on penalties: record the winner so the bracket pins correctly
        if match.get('stage') != 'group' and s1 == s2 and shootout_winner:
            match['score']['winner'] = shootout_winner
        applied.append(f"{match['id']} {match['team1']} {s1}-{s2} {match['team2']}")
    except Exception as ex:
        print(f"Skipped one event on parse error: {ex}")

if not applied:
    out(False, f"Feed reached; no newly completed matches among {len(pending)} pending.")

data['meta']['asOf'] = now.strftime('%Y-%m-%d')
done = sum(1 for m in data['matches'] if m['status'] == 'completed')
data['meta']['asOfNote'] = (f"Results through {done} matches, auto-synced from the ESPN public feed "
                            f"{now.strftime('%Y-%m-%d %H:%M UTC')}. Probabilities recompute in your browser from this data.")
new = "// Generated by transform.py — do not edit by hand. Patch results here, then rebuild.\n"
new += "const WC_DATA = " + json.dumps(data, ensure_ascii=False, indent=1) + ";\n"
new += "if (typeof module !== 'undefined') module.exports = { WC_DATA };\n"
tmp = DATA + '.tmp'
with open(tmp, 'w') as f:
    f.write(new)
os.replace(tmp, DATA)            # atomic: a crash mid-write can't corrupt data.js
out(True, "Applied: " + "; ".join(applied))
