#!/usr/bin/env python3
"""Populate per-match team xG (actual expected goals) from ESPN's free *core* API
and patch src/data.js. Replaces the dropped paid StatsAPI xG feed (TheStatsAPI
monthly quota exhausted 20 Jun 2026). ESPN is the same provider already feeding
the scores, so there is no cross-provider seam.

The team-total xG is NOT in the site summary feed (that only carries a few
per-player leader values); it lives in the core API per-competitor statistics:
  .../events/{id}/competitions/{id}/competitors/{teamId}/statistics
as a stat object {"name":"expectedGoals","value":<float>}. Stdlib only.

Usage: fetch_xg.py [--all]
  default: only completed matches that have no xg yet.
  --all:   refresh every completed match (full re-pull; one consistent model).

Defensive: writes m['xg'] only when BOTH teams resolve to a numeric xG in the
sane range [0, 8]; otherwise it skips the match and logs, and never overwrites
an existing good value with a blank.
"""
import json, os, re, sys, urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, "src", "data.js")
MAP = os.path.join(ROOT, "src", "espn-map.json")
SB = "https://site.api.espn.com/apis/site/v2/sports/soccer/fifa.world/scoreboard?dates={d}"
STAT = ("https://sports.core.api.espn.com/v2/sports/soccer/leagues/fifa.world/"
        "events/{e}/competitions/{e}/competitors/{t}/statistics")
HDR = {"User-Agent": "worldcup-2026-xg/1.0"}
ALL = "--all" in sys.argv
XG_MIN, XG_MAX = 0.0, 8.0

def get(url):
    try:
        with urllib.request.urlopen(urllib.request.Request(url, headers=HDR), timeout=30) as r:
            return json.load(r)
    except Exception:
        return None

def find_stat(obj, name):
    """Depth-first search for a stat object {'name': name, 'value': <number>}."""
    stack = [obj]
    while stack:
        x = stack.pop()
        if isinstance(x, dict):
            if x.get("name") == name and isinstance(x.get("value"), (int, float)):
                return float(x["value"])
            stack.extend(x.values())
        elif isinstance(x, list):
            stack.extend(x)
    return None

raw = open(DATA).read()
m0 = re.search(r"const WC_DATA = (\{.*?\});\nif \(typeof module", raw, re.S)
if not m0:
    sys.exit("ERROR: could not parse WC_DATA from src/data.js (shape changed?)")
data = json.loads(m0.group(1))
idmap = json.load(open(MAP))["teamIds"]   # ESPN team id (str) -> our code

played = [m for m in data["matches"] if m["status"] == "completed" and m.get("score")]
todo = [m for m in played if ALL or not m.get("xg")]

# group by ET date; one scoreboard call per date resolves event id + the two
# ESPN team ids, which the core stats endpoint needs.
by_date = {}
for m in todo:
    by_date.setdefault(m["dateET"][:10].replace("-", ""), []).append(m)

set_n, skip = 0, []
for d, ms in by_date.items():
    sb = get(SB.format(d=d))
    if not sb:
        skip += [f"{m['team1']}-{m['team2']} (scoreboard {d} unavailable)" for m in ms]
        continue
    # event id -> {our_code: espn_team_id}
    ev_by_pair = {}
    for e in sb.get("events", []):
        try:
            comp = e["competitions"][0]
            cmap = {}
            for c in comp["competitors"]:
                tid = str(c["team"]["id"])
                cmap[idmap.get(tid) or c["team"].get("abbreviation")] = tid
            ev_by_pair[frozenset(cmap)] = (e["id"], cmap)
        except Exception:
            continue
    for m in ms:
        hit = ev_by_pair.get(frozenset((m["team1"], m["team2"])))
        if not hit:
            skip.append(f"{m['team1']}-{m['team2']} (no ESPN event match)")
            continue
        eid, cmap = hit
        vals = {}
        for side in ("team1", "team2"):
            tid = cmap.get(m[side])
            st = get(STAT.format(e=eid, t=tid)) if tid else None
            xg = find_stat(st, "expectedGoals") if st else None
            if xg is not None and XG_MIN <= xg <= XG_MAX:
                vals[side] = round(xg, 2)
        if len(vals) == 2:                       # only write when BOTH are good
            m["xg"] = {"team1": vals["team1"], "team2": vals["team2"], "src": "espn"}
            set_n += 1
        else:
            skip.append(f"{m['team1']}-{m['team2']} (xG missing/out-of-range: {vals or 'none'})")

new = "// Generated by transform.py — do not edit by hand. Patch results here, then rebuild.\n"
new += "const WC_DATA = " + json.dumps(data, ensure_ascii=False, indent=1) + ";\n"
new += "if (typeof module !== 'undefined') module.exports = { WC_DATA };\n"
tmp = DATA + ".tmp"
with open(tmp, "w") as f:
    f.write(new)
os.replace(tmp, DATA)            # atomic: a crash mid-write can't corrupt data.js

print(f"ESPN xG: set on {set_n} match(es); {len(skip)} skipped")
for s in skip:
    print("  skip:", s)
gh = os.environ.get("GITHUB_OUTPUT")
if gh:
    with open(gh, "a") as f: f.write(f"changed={'true' if set_n else 'false'}\n")
