#!/usr/bin/env python3
"""Generate and resolve the 32-match knockout bracket into src/data.js.

The data ships only the 72 group matches plus r32Template (the official R32
pairings, in bracket order, with FIFA match numbers 73-88). This tool builds the
remaining knockout fixtures (R32 with real teams, then R16/QF/SF/3rd/Final as a
routed skeleton) and resolves each round's teams from completed results as the
tournament progresses. Idempotent: safe to run every cycle; never overwrites a
recorded score. Stdlib only, mirrors fetch_scores.py's data.js read/write.

FIFA alignment:
  * Routing R32 -> R16 -> QF -> SF -> Final is the sequential pairing of
    r32Template's bracket order, the same routing src/engine.js uses and the one
    meta.bracketNote records as verified against the published schedule.
  * Group-determined R32 slots (group winner / runner-up) are filled
    deterministically from final standings (pts, GD, GF), the engine's order.
  * The eight "winner vs 3rd" slots are NOT derivable from the allow-lists alone
    (all 495 qualifying-group combinations admit more than one valid assignment),
    so the official third-place assignment is taken from, in order: an explicit
    --thirds override, then the ESPN feed's published R32 fixtures. It is never
    guessed. Without a source the third slots stay TBD and the tool warns.

Usage:
  python3 scripts/generate_knockout.py                 # ensure + resolve (real run; needs groups complete)
  python3 scripts/generate_knockout.py --thirds '{"R32-3":"CRO",...}'   # supply official 3rd assignment
  python3 scripts/generate_knockout.py --from-feed     # read official R32 pairings from ESPN
  python3 scripts/generate_knockout.py --selftest      # exercise the machinery on simulated results; writes nothing
  python3 scripts/generate_knockout.py --force         # build skeleton even if groups incomplete (TBD teams)
"""
import json, os, re, sys, copy, datetime, urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, 'src', 'data.js')
MAP = os.path.join(ROOT, 'src', 'espn-map.json')
FEED = "https://site.api.espn.com/apis/site/v2/sports/soccer/fifa.world/scoreboard?dates={d}"

# Nominal R16+ scheduling. Match numbers continue the official sequence
# (R32 = 73-88). Per-match venue/date for R16+ are NOT in the shipped data and
# are marked scheduleApprox; confirm against FIFA when the bracket is set.
R16_VENUES = ['HOU', 'PHI', 'NYNJ', 'MEX', 'DAL', 'SEA', 'ATL', 'BCP']
R16_DATES = ['2026-07-04', '2026-07-04', '2026-07-05', '2026-07-05',
             '2026-07-06', '2026-07-06', '2026-07-07', '2026-07-07']
QF_VENUES = ['BOS', 'LA', 'MIA', 'KC']
QF_DATES = ['2026-07-09', '2026-07-10', '2026-07-10', '2026-07-11']
SF_VENUES = ['DAL', 'ATL']
SF_DATES = ['2026-07-14', '2026-07-15']


# ---------- data.js I/O (identical conventions to fetch_scores.py) ----------
def load_data():
    raw = open(DATA).read()
    m0 = re.search(r'const WC_DATA = (\{.*?\});\nif \(typeof module', raw, re.S)
    if not m0:
        sys.exit("FATAL: could not parse src/data.js (regex drift).")
    return json.loads(m0.group(1))


def save_data(data):
    new = "// Generated by transform.py — do not edit by hand. Patch results here, then rebuild.\n"
    new += "const WC_DATA = " + json.dumps(data, ensure_ascii=False, indent=1) + ";\n"
    new += "if (typeof module !== 'undefined') module.exports = { WC_DATA };\n"
    tmp = DATA + '.tmp'
    with open(tmp, 'w') as f:
        f.write(new)
    os.replace(tmp, DATA)        # atomic: a crash mid-write can't corrupt data.js


# ---------- standings (engine order: pts, GD, GF) ----------
def standings(data):
    st = {t['code']: {'P': 0, 'W': 0, 'D': 0, 'GF': 0, 'GA': 0, 'Pts': 0, 'grp': t['group']}
          for t in data['teams']}
    for m in data['matches']:
        if m.get('stage') != 'group' or m.get('status') != 'completed' or not m.get('score'):
            continue
        a, b = st[m['team1']], st[m['team2']]
        s1, s2 = m['score']['team1'], m['score']['team2']
        a['P'] += 1; b['P'] += 1; a['GF'] += s1; a['GA'] += s2; b['GF'] += s2; b['GA'] += s1
        if s1 > s2: a['Pts'] += 3
        elif s2 > s1: b['Pts'] += 3
        else: a['Pts'] += 1; b['Pts'] += 1
    for c in st:
        st[c]['GD'] = st[c]['GF'] - st[c]['GA']
    groups = {}
    for c, v in st.items():
        groups.setdefault(v['grp'], []).append(c)
    # completed group results for the head-to-head tiebreak
    played = [(m['team1'], m['team2'], m['score']['team1'], m['score']['team2'])
              for m in data['matches']
              if m.get('stage') == 'group' and m.get('status') == 'completed' and m.get('score')]
    key = lambda c: (st[c]['Pts'], st[c]['GD'], st[c]['GF'])

    def h2h_reorder(codes):
        # After Pts->GD->GF, order any still-level cluster by the head-to-head mini-table
        # (FIFA: H2H pts -> H2H GD -> H2H GF) over matches among the tied teams only.
        # Residual ties keep their prior order (fair-play / lots not modelled). Mirrors
        # engine.js currentTables so the script, the model and the board agree.
        out, i = [], 0
        while i < len(codes):
            j = i
            while j + 1 < len(codes) and key(codes[j + 1]) == key(codes[i]):
                j += 1
            tied = codes[i:j + 1]
            if len(tied) > 1:
                s = set(tied)
                h = {c: {'p': 0, 'gd': 0, 'gf': 0} for c in tied}
                for a, b, ga, gb in played:
                    if a in s and b in s:
                        h[a]['gf'] += ga; h[a]['gd'] += ga - gb
                        h[b]['gf'] += gb; h[b]['gd'] += gb - ga
                        if ga > gb: h[a]['p'] += 3
                        elif gb > ga: h[b]['p'] += 3
                        else: h[a]['p'] += 1; h[b]['p'] += 1
                tied.sort(key=lambda c: (h[c]['p'], h[c]['gd'], h[c]['gf']), reverse=True)
            out.extend(tied)
            i = j + 1
        return out

    order = {g: h2h_reorder(sorted(cs, key=key, reverse=True)) for g, cs in groups.items()}
    return st, order


def groups_complete(data):
    return all(m.get('status') == 'completed' and m.get('score')
               for m in data['matches'] if m.get('stage') == 'group')


def best_thirds(st, order):
    thirds = [order[g][2] for g in sorted(order)]
    thirds.sort(key=lambda c: (st[c]['Pts'], st[c]['GD'], st[c]['GF']), reverse=True)
    return thirds[:8]  # the eight that qualify, ranked


# ---------- third assignment from an authoritative source ----------
def thirds_from_feed(data, idmap):
    """Read the official R32 third opponents from ESPN's published fixtures."""
    rev = {v: k for k, v in idmap.items()}  # code -> espn id (unused; kept for clarity)
    dates = sorted({s['date'] for s in data['r32Template']})  # display strings; not used for query
    # query the R32 calendar window
    span = "20260628-20260703"
    try:
        req = urllib.request.Request(FEED.format(d=span), headers={'User-Agent': 'worldcup-2026-knockout'})
        evs = json.load(urllib.request.urlopen(req, timeout=30)).get('events', [])
    except Exception as e:
        print(f"  feed unreachable ({e}); third slots left TBD.")
        return {}
    # Only real team codes count. A half-published ESPN bracket lists not-yet-decided
    # sides as placeholders ("3RD", "1A", "TBD"); accepting one poisons the assignment
    # and (pre-fix) hard-failed the whole build. Filtering to the actual 48-team code
    # set means a placeholder pairing is simply skipped until the feed fills it in.
    valid = {t['code'] for t in data['teams']}
    pairs = []
    for e in evs:
        try:
            comp = e['competitions'][0]
            codes = [idmap.get(str(c['team']['id'])) or c['team'].get('abbreviation')
                     for c in comp['competitors']]
            codes = [c for c in codes if c in valid]
            if len(codes) == 2:
                pairs.append(set(codes))
        except Exception:
            continue
    # for each third slot, the group-winner side is known; the opponent is the third
    out = {}
    _, order = standings(data)
    for slot in data['r32Template']:
        third_side = 'a' if slot['a']['type'] == 'third' else 'b' if slot['b']['type'] == 'third' else None
        if not third_side:
            continue
        gside = slot['b'] if third_side == 'a' else slot['a']
        known = order[gside['group']][gside['place'] - 1]
        for p in pairs:
            if known in p:
                opp = (p - {known}).pop()
                if opp in valid and opp != known:
                    out[slot['id']] = opp
                break
    return out


def validate_thirds(data, st, order, assign):
    """Every assigned third must be a genuine qualifying third and in the slot's allow-list."""
    qualifying = set(best_thirds(st, order))
    problems = []
    for slot in data['r32Template']:
        side = slot['a'] if slot['a']['type'] == 'third' else slot['b'] if slot['b']['type'] == 'third' else None
        if not side:
            continue
        t = assign.get(slot['id'])
        if not t:
            continue
        if t not in qualifying:
            problems.append(f"{slot['id']}: {t} is not a qualifying third")
        elif st[t]['grp'] not in side['groups']:
            problems.append(f"{slot['id']}: {t} (group {st[t]['grp']}) not allowed here ({''.join(side['groups'])})")
    used = [v for v in assign.values()]
    if len(set(used)) != len(used):
        problems.append("a third is assigned to more than one slot")
    return problems


# ---------- bracket construction ----------
def bracket_skeleton(data, order, thirds_assign):
    """Build all 32 KO match objects: R32 with teams (where known) + routed R16..Final."""
    tpl = data['r32Template']  # already in bracket order

    ko = []
    r32_ids = []
    for slot in tpl:
        t1 = (order[slot['a']['group']][slot['a']['place'] - 1] if slot['a']['type'] == 'group' and order
              else thirds_assign.get(slot['id']) if slot['a']['type'] == 'third' else None)
        t2 = (order[slot['b']['group']][slot['b']['place'] - 1] if slot['b']['type'] == 'group' and order
              else thirds_assign.get(slot['id']) if slot['b']['type'] == 'third' else None)
        ko.append({
            'id': slot['id'], 'stage': 'r32', 'round': 'r32', 'matchNo': slot['matchNo'],
            'dateET': _date_et(slot['date']), 'venueId': slot['venueId'],
            'team1': t1, 'team2': t2, 'status': 'pending',
            'feeds': None, 'label': slot.get('label'),
        })
        r32_ids.append(slot['id'])

    def layer(prefix, feed_ids, start_no, venues, dates):
        ids = []
        for i in range(len(feed_ids) // 2):
            mid = f"{prefix}-{i + 1}"
            ko.append({
                'id': mid, 'stage': prefix.lower(), 'round': prefix.lower(),
                'matchNo': start_no + i,
                'dateET': _date_et(dates[i]) if dates else None,
                'venueId': venues[i] if venues else None,
                'team1': None, 'team2': None, 'status': 'pending',
                'feeds': [feed_ids[2 * i], feed_ids[2 * i + 1]],
                'scheduleApprox': True,
            })
            ids.append(mid)
        return ids

    r16_ids = layer('R16', r32_ids, 89, R16_VENUES, R16_DATES)
    qf_ids = layer('QF', r16_ids, 97, QF_VENUES, QF_DATES)
    sf_ids = layer('SF', qf_ids, 101, SF_VENUES, SF_DATES)
    # third-place game: SF losers; final: SF winners
    ko.append({'id': 'THIRD', 'stage': 'third', 'round': 'third', 'matchNo': 103,
               'dateET': _date_et('2026-07-18'), 'venueId': 'MIA',
               'team1': None, 'team2': None, 'status': 'pending',
               'feeds': sf_ids, 'losers': True, 'scheduleApprox': True})
    ko.append({'id': 'FINAL', 'stage': 'final', 'round': 'final', 'matchNo': 104,
               'dateET': _date_et('2026-07-19'), 'venueId': 'NYNJ',
               'team1': None, 'team2': None, 'status': 'pending',
               'feeds': sf_ids, 'scheduleApprox': True})
    return ko


def _date_et(d):
    """Return a full ISO datetime with the tournament's -04:00 ET offset, so
    fetch_scores.py's datetime.fromisoformat() parses every knockout match.
    Accepts an ISO date ('2026-07-04') or the template's display form ('Mon Jun 29')."""
    if not isinstance(d, str):
        return d
    if re.match(r'\d{4}-\d{2}-\d{2}$', d):
        return d + "T16:00:00-04:00"
    try:  # 'Mon Jun 29' -> 2026-06-29 (the tournament runs entirely in 2026)
        dt = datetime.datetime.strptime(d.strip() + " 2026", "%a %b %d %Y")
        return dt.strftime("%Y-%m-%d") + "T16:00:00-04:00"
    except ValueError:
        return d


def winner_of(m):
    sc = m.get('score')
    if not sc:
        return None
    if sc.get('winner'):
        return sc['winner']
    if sc['team1'] > sc['team2']:
        return m['team1']
    if sc['team2'] > sc['team1']:
        return m['team2']
    return None  # KO draw with no recorded sh‑out winner: unresolved


def loser_of(m):
    w = winner_of(m)
    if not w or not m.get('team1') or not m.get('team2'):
        return None
    return m['team2'] if w == m['team1'] else m['team1']


def resolve(ko):
    """Fill team1/team2 of any KO match whose feeders are decided. Idempotent."""
    by_id = {m['id']: m for m in ko}
    changed = 0
    # process in dependency order: R32 first, then by matchNo
    for m in sorted(ko, key=lambda x: x['matchNo']):
        if not m.get('feeds'):
            continue
        if m['status'] == 'completed':
            continue
        fa, fb = (by_id[i] for i in m['feeds'])
        if m.get('losers'):
            a, b = loser_of(fa), loser_of(fb)
        else:
            a, b = winner_of(fa), winner_of(fb)
        for key, val in (('team1', a), ('team2', b)):
            if val and m.get(key) != val:
                m[key] = val; changed += 1
    return changed


def merge_into_data(data, ko):
    """Replace non-group matches with the rebuilt KO set, preserving recorded scores."""
    prev = {m['id']: m for m in data['matches'] if m.get('stage') != 'group'}
    for m in ko:
        old = prev.get(m['id'])
        if not old:
            continue
        if old.get('status') == 'completed' and old.get('score'):
            m['status'] = 'completed'; m['score'] = old['score']
            m['team1'] = old.get('team1', m['team1'])
            m['team2'] = old.get('team2', m['team2'])
        # Never regress an already-known team back to TBD. A cycle without a third-place
        # source (e.g. the ESPN feed was momentarily unreachable) rebuilds the eight
        # "winner vs 3rd" slots as null; keep the previously-assigned opponents instead
        # of blanking a live bracket. resolve() still fills genuinely-new slots.
        if not m.get('team1') and old.get('team1'):
            m['team1'] = old['team1']
        if not m.get('team2') and old.get('team2'):
            m['team2'] = old['team2']
    groups = [m for m in data['matches'] if m.get('stage') == 'group']
    data['matches'] = groups + ko
    return data


# ---------- self-test: exercise everything on simulated results, write nothing ----------
def selftest():
    data = load_data()
    sim = copy.deepcopy(data)
    # deterministically fill every group match with a pseudo score
    seed = 1
    for m in sim['matches']:
        if m.get('stage') == 'group':
            seed = (seed * 1103515245 + 12345) & 0x7fffffff
            s1 = seed % 4
            seed = (seed * 1103515245 + 12345) & 0x7fffffff
            s2 = seed % 4
            m['status'] = 'completed'; m['score'] = {'team1': s1, 'team2': s2}
    assert groups_complete(sim), "selftest failed to complete groups"
    st, order = standings(sim)
    thirds = best_thirds(st, order)
    # provisional assignment purely to exercise structure (bipartite matching on allow-lists)
    assign = _provisional_thirds(sim, st, order, thirds)
    probs = validate_thirds(sim, st, order, assign)
    assert not probs, f"provisional thirds invalid: {probs}"
    ko = bracket_skeleton(sim, order, assign)
    assert len(ko) == 32, f"expected 32 KO matches, got {len(ko)}"
    # simulate the whole bracket to a single champion
    rounds = ['r32', 'r16', 'qf', 'sf']
    by_id = {m['id']: m for m in ko}
    for rnd in rounds:
        for m in [x for x in ko if x['round'] == rnd]:
            if m['team1'] is None:  # resolve from feeders first
                resolve(ko)
            seed_local = sum(ord(c) for c in (m['team1'] or '') + (m['team2'] or ''))
            m['status'] = 'completed'
            m['score'] = {'team1': 2, 'team2': 1} if seed_local % 2 else {'team1': 0, 'team2': 1}
        resolve(ko)
    fin = by_id['FINAL']; resolve(ko)
    fin['status'] = 'completed'; fin['score'] = {'team1': 1, 'team2': 0}
    champ = winner_of(fin)
    merged = merge_into_data(copy.deepcopy(sim), ko)
    total = len(merged['matches']); ko_n = len([m for m in merged['matches'] if m['stage'] != 'group'])
    print("SELFTEST")
    print(f"  groups completed, standings computed; 8 qualifying thirds: {' '.join(thirds)}")
    print(f"  provisional third assignment valid: {len(assign)}/8 slots, no allow-list violations")
    print(f"  bracket built: {len(ko)} KO matches (R32 16, R16 8, QF 4, SF 2, 3rd 1, final 1)")
    print(f"  routing resolved end-to-end to a single champion: {champ}")
    print(f"  merged match count: {total} (72 group + {ko_n} knockout) — {'OK' if total == 104 and ko_n == 32 else 'FAIL'}")
    print("  wrote nothing (selftest).")
    return 0 if (total == 104 and ko_n == 32 and champ) else 1


def _provisional_thirds(data, st, order, thirds):
    """Bipartite matching of qualifying thirds to third-slots on allow-lists.
    Used ONLY for --selftest and as a clearly-flagged fallback; NOT FIFA-authoritative."""
    slots = []
    for s in data['r32Template']:
        side = s['a'] if s['a']['type'] == 'third' else s['b'] if s['b']['type'] == 'third' else None
        if side:
            slots.append((s['id'], side['groups']))
    grp_of = {c: st[c]['grp'] for c in thirds}
    assign = {}
    used = set()

    def rec(i):
        if i == len(slots):
            return True
        sid, allow = slots[i]
        for c in thirds:
            if c not in used and grp_of[c] in allow:
                used.add(c); assign[sid] = c
                if rec(i + 1):
                    return True
                used.discard(c); del assign[sid]
        return False
    rec(0)
    return assign


# ---------- main ----------
def main():
    args = sys.argv[1:]
    if '--selftest' in args:
        return selftest()

    data = load_data()
    force = '--force' in args
    if not groups_complete(data) and not force:
        done = sum(1 for m in data['matches'] if m.get('stage') == 'group' and m.get('status') == 'completed')
        print(f"Group stage not complete ({done}/72). Nothing to do. Re-run when groups finish, "
              f"or pass --force to build a TBD skeleton.")
        _emit_changed(False)
        return 0

    st, order = (standings(data) if groups_complete(data) else ({}, {}))

    # third assignment, from an authoritative source only
    assign = {}
    if '--thirds' in args:
        assign = json.loads(args[args.index('--thirds') + 1])
        print(f"Third assignment supplied via --thirds ({len(assign)} slots).")
    elif '--from-feed' in args:
        idmap = json.load(open(MAP))['teamIds']
        assign = thirds_from_feed(data, idmap)
        print(f"Third assignment read from ESPN feed ({len(assign)} slots).")

    if order and assign:
        probs = validate_thirds(data, st, order, assign)
        if probs and '--thirds' in args:
            # An explicit human-supplied assignment that fails validation is a real
            # mistake worth failing loudly on.
            sys.exit("Third assignment rejected:\n  " + "\n  ".join(probs))
        if probs:
            # Feed-derived assignment: NEVER abort. A half-published ESPN bracket
            # (placeholder codes, a duplicate) must not strand the whole build, the
            # 28 June 2026 failure. Drop the offending slots to TBD and build the rest;
            # a later cycle fills them once the feed is clean. (The valid-code filter
            # in thirds_from_feed normally prevents ever reaching here.)
            bad = {p.split(':', 1)[0].strip() for p in probs if p.startswith('R32-')}
            for sid in bad:
                assign.pop(sid, None)
            if any(not p.startswith('R32-') for p in probs) or validate_thirds(data, st, order, assign):
                assign = {}  # non-slot-specific problem (e.g. duplicate): drop them all
            print(f"WARNING: feed third assignment partially invalid; left "
                  f"{8 - len(assign)} 'winner vs 3rd' slot(s) TBD and continued (not aborting).")
    elif order and not assign:
        print("WARNING: no third-place source (--thirds or --from-feed). The eight "
              "'winner vs 3rd' R32 slots will be left TBD. Group-determined slots and "
              "the full R16..Final routing are still built.")

    # Snapshot the existing knockout matches so we can tell whether this run actually
    # changes the bracket — the CI signal the workflow gates its rebuild/commit on,
    # and the guard that keeps idempotent cycles from making empty commits.
    before = json.dumps([m for m in data['matches'] if m.get('stage') != 'group'],
                        sort_keys=True, ensure_ascii=False)

    ko = bracket_skeleton(data, order, assign)
    # Merge BEFORE resolving: bracket_skeleton builds fresh, score-less match
    # objects, so resolve() can only propagate teams to R16+ once the recorded
    # scores have been copied back onto the completed feeders. Resolving first
    # (the old order) left every round past R32 permanently TBD.
    data = merge_into_data(data, ko)
    resolved = resolve(ko)

    ko_n = len([m for m in data['matches'] if m['stage'] != 'group'])
    if ko_n != 32:
        sys.exit(f"FATAL: expected 32 knockout matches, built {ko_n}.")
    after = json.dumps([m for m in data['matches'] if m.get('stage') != 'group'],
                       sort_keys=True, ensure_ascii=False)
    changed = before != after
    if changed:
        save_data(data)
    _emit_changed(changed)
    tbd = len([m for m in ko if m['stage'] == 'r32' and (not m['team1'] or not m['team2'])])
    print(f"{'Wrote' if changed else 'No change to'} {ko_n} knockout matches "
          f"(resolved {resolved} team slots from completed feeders). {tbd} R32 slots still TBD."
          + (" Run build.py to publish." if changed else ""))
    return 0


def _emit_changed(changed):
    """Write a changed=true|false line to $GITHUB_OUTPUT so the workflow can gate its
    rebuild/commit on this step even on a cycle with no new score (the catch-up path)."""
    gh = os.environ.get('GITHUB_OUTPUT')
    if gh:
        with open(gh, 'a') as f:
            f.write(f"changed={'true' if changed else 'false'}\n")


if __name__ == '__main__':
    sys.exit(main())
