// Generated by transform.py — do not edit by hand. Patch results here, then rebuild.
const WC_DATA = {
 "meta": {
  "title": "World Cup 2026 — Probability Centre",
  "version": "1.0",
  "asOf": "2026-06-12",
  "asOfNote": "Results through matchday 1 (11 June 2026). Probabilities recompute in your browser from this data.",
  "sources": [
   {
    "name": "FIFA fixtures and standings",
    "url": "https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026/scores-fixtures"
   },
   {
    "name": "Base ratings: Elo-style ratings derived from FIFA rankings (11 June 2026 snapshot)",
    "url": "https://www.fifa.com/en/ranking/men"
   }
  ],
  "bracketNote": "R32 slots in official bracket order (FIFA match numbers); sequential pairing reproduces the official R16/QF/SF routing to the 19 July MetLife final. Verified against the published knockout schedule, 12 June 2026."
 },
 "teams": [
  {
   "code": "MEX",
   "name": "Mexico",
   "flag": "🇲🇽",
   "group": "A",
   "fifaRank": 14,
   "confed": "CONCACAF",
   "baseRating": 1978.0,
   "preProb": 1.72,
   "marketProb": 1.28
  },
  {
   "code": "RSA",
   "name": "South Africa",
   "flag": "🇿🇦",
   "group": "A",
   "fifaRank": 60,
   "confed": "CAF",
   "baseRating": 1732.4,
   "preProb": 0.06,
   "marketProb": 0.08
  },
  {
   "code": "KOR",
   "name": "Korea Republic",
   "flag": "🇰🇷",
   "group": "A",
   "fifaRank": 25,
   "confed": "AFC",
   "baseRating": 1883.8,
   "preProb": 0.39,
   "marketProb": 0.21
  },
  {
   "code": "CZE",
   "name": "Czechia",
   "flag": "🇨🇿",
   "group": "A",
   "fifaRank": 40,
   "confed": "UEFA",
   "baseRating": 1824.7,
   "preProb": 0.42,
   "marketProb": 0.34
  },
  {
   "code": "CAN",
   "name": "Canada",
   "flag": "🇨🇦",
   "group": "B",
   "fifaRank": 30,
   "confed": "CONCACAF",
   "baseRating": 1890.4,
   "preProb": 0.55,
   "marketProb": 0.42
  },
  {
   "code": "BIH",
   "name": "Bosnia and Herzegovina",
   "flag": "🇧🇦",
   "group": "B",
   "fifaRank": 64,
   "confed": "UEFA",
   "baseRating": 1721.7,
   "preProb": 0.2,
   "marketProb": 0.17
  },
  {
   "code": "QAT",
   "name": "Qatar",
   "flag": "🇶🇦",
   "group": "B",
   "fifaRank": 56,
   "confed": "AFC",
   "baseRating": 1750.8,
   "preProb": 0.12,
   "marketProb": 0.06
  },
  {
   "code": "SUI",
   "name": "Switzerland",
   "flag": "🇨🇭",
   "group": "B",
   "fifaRank": 19,
   "confed": "UEFA",
   "baseRating": 1931.3,
   "preProb": 1.43,
   "marketProb": 1.28
  },
  {
   "code": "BRA",
   "name": "Brazil",
   "flag": "🇧🇷",
   "group": "C",
   "fifaRank": 6,
   "confed": "CONMEBOL",
   "baseRating": 2032.3,
   "preProb": 6.8,
   "marketProb": 8.03
  },
  {
   "code": "MAR",
   "name": "Morocco",
   "flag": "🇲🇦",
   "group": "C",
   "fifaRank": 7,
   "confed": "CAF",
   "baseRating": 1987.0,
   "preProb": 1.92,
   "marketProb": 1.65
  },
  {
   "code": "HAI",
   "name": "Haiti",
   "flag": "🇭🇹",
   "group": "C",
   "fifaRank": 83,
   "confed": "CONCACAF",
   "baseRating": 1640.0,
   "preProb": 0.05,
   "marketProb": 0.03
  },
  {
   "code": "SCO",
   "name": "Scotland",
   "flag": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
   "group": "C",
   "fifaRank": 42,
   "confed": "UEFA",
   "baseRating": 1816.7,
   "preProb": 0.42,
   "marketProb": 0.42
  },
  {
   "code": "USA",
   "name": "United States",
   "flag": "🇺🇸",
   "group": "D",
   "fifaRank": 17,
   "confed": "CONCACAF",
   "baseRating": 1962.7,
   "preProb": 1.51,
   "marketProb": 1.39
  },
  {
   "code": "PAR",
   "name": "Paraguay",
   "flag": "🇵🇾",
   "group": "D",
   "fifaRank": 41,
   "confed": "CONMEBOL",
   "baseRating": 1819.2,
   "preProb": 0.37,
   "marketProb": 0.28
  },
  {
   "code": "AUS",
   "name": "Australia",
   "flag": "🇦🇺",
   "group": "D",
   "fifaRank": 27,
   "confed": "AFC",
   "baseRating": 1872.0,
   "preProb": 0.27,
   "marketProb": 0.14
  },
  {
   "code": "TUR",
   "name": "Türkiye",
   "flag": "🇹🇷",
   "group": "D",
   "fifaRank": 22,
   "confed": "UEFA",
   "baseRating": 1911.9,
   "preProb": 1.04,
   "marketProb": 0.93
  },
  {
   "code": "GER",
   "name": "Germany",
   "flag": "🇩🇪",
   "group": "E",
   "fifaRank": 10,
   "confed": "UEFA",
   "baseRating": 2010.1,
   "preProb": 5.73,
   "marketProb": 5.62
  },
  {
   "code": "CUW",
   "name": "Curaçao",
   "flag": "🇨🇼",
   "group": "E",
   "fifaRank": 82,
   "confed": "CONCACAF",
   "baseRating": 1644.0,
   "preProb": 0.05,
   "marketProb": 0.03
  },
  {
   "code": "CIV",
   "name": "Côte d'Ivoire",
   "flag": "🇨🇮",
   "group": "E",
   "fifaRank": 33,
   "confed": "CAF",
   "baseRating": 1853.6,
   "preProb": 0.45,
   "marketProb": 0.34
  },
  {
   "code": "ECU",
   "name": "Ecuador",
   "flag": "🇪🇨",
   "group": "E",
   "fifaRank": 23,
   "confed": "CONMEBOL",
   "baseRating": 1909.4,
   "preProb": 1.11,
   "marketProb": 1.04
  },
  {
   "code": "NED",
   "name": "Netherlands",
   "flag": "🇳🇱",
   "group": "F",
   "fifaRank": 8,
   "confed": "UEFA",
   "baseRating": 2007.5,
   "preProb": 4.23,
   "marketProb": 4.01
  },
  {
   "code": "JPN",
   "name": "Japan",
   "flag": "🇯🇵",
   "group": "F",
   "fifaRank": 18,
   "confed": "AFC",
   "baseRating": 1935.5,
   "preProb": 1.44,
   "marketProb": 1.5
  },
  {
   "code": "SWE",
   "name": "Sweden",
   "flag": "🇸🇪",
   "group": "F",
   "fifaRank": 38,
   "confed": "UEFA",
   "baseRating": 1840.3,
   "preProb": 0.7,
   "marketProb": 0.7
  },
  {
   "code": "TUN",
   "name": "Tunisia",
   "flag": "🇹🇳",
   "group": "F",
   "fifaRank": 45,
   "confed": "CAF",
   "baseRating": 1799.0,
   "preProb": 0.24,
   "marketProb": 0.16
  },
  {
   "code": "BEL",
   "name": "Belgium",
   "flag": "🇧🇪",
   "group": "G",
   "fifaRank": 9,
   "confed": "UEFA",
   "baseRating": 1986.3,
   "preProb": 2.47,
   "marketProb": 2.06
  },
  {
   "code": "EGY",
   "name": "Egypt",
   "flag": "🇪🇬",
   "group": "G",
   "fifaRank": 29,
   "confed": "CAF",
   "baseRating": 1868.7,
   "preProb": 0.42,
   "marketProb": 0.28
  },
  {
   "code": "IRN",
   "name": "IR Iran",
   "flag": "🇮🇷",
   "group": "G",
   "fifaRank": 20,
   "confed": "AFC",
   "baseRating": 1901.3,
   "preProb": 0.31,
   "marketProb": 0.12
  },
  {
   "code": "NZL",
   "name": "New Zealand",
   "flag": "🇳🇿",
   "group": "G",
   "fifaRank": 85,
   "confed": "OFC",
   "baseRating": 1632.8,
   "preProb": 0.07,
   "marketProb": 0.05
  },
  {
   "code": "ESP",
   "name": "Spain",
   "flag": "🇪🇸",
   "group": "H",
   "fifaRank": 2,
   "confed": "UEFA",
   "baseRating": 2075.3,
   "preProb": 13.83,
   "marketProb": 15.33
  },
  {
   "code": "CPV",
   "name": "Cabo Verde",
   "flag": "🇨🇻",
   "group": "H",
   "fifaRank": 67,
   "confed": "CAF",
   "baseRating": 1706.8,
   "preProb": 0.12,
   "marketProb": 0.08
  },
  {
   "code": "KSA",
   "name": "Saudi Arabia",
   "flag": "🇸🇦",
   "group": "H",
   "fifaRank": 61,
   "confed": "AFC",
   "baseRating": 1731.5,
   "preProb": 0.14,
   "marketProb": 0.09
  },
  {
   "code": "URU",
   "name": "Uruguay",
   "flag": "🇺🇾",
   "group": "H",
   "fifaRank": 16,
   "confed": "CONMEBOL",
   "baseRating": 1944.5,
   "preProb": 1.5,
   "marketProb": 1.28
  },
  {
   "code": "FRA",
   "name": "France",
   "flag": "🇫🇷",
   "group": "I",
   "fifaRank": 3,
   "confed": "UEFA",
   "baseRating": 2069.1,
   "preProb": 13.09,
   "marketProb": 14.66
  },
  {
   "code": "SEN",
   "name": "Senegal",
   "flag": "🇸🇳",
   "group": "I",
   "fifaRank": 15,
   "confed": "CAF",
   "baseRating": 1944.1,
   "preProb": 1.25,
   "marketProb": 0.93
  },
  {
   "code": "IRQ",
   "name": "Iraq",
   "flag": "🇮🇶",
   "group": "I",
   "fifaRank": 57,
   "confed": "AFC",
   "baseRating": 1746.4,
   "preProb": 0.11,
   "marketProb": 0.06
  },
  {
   "code": "NOR",
   "name": "Norway",
   "flag": "🇳🇴",
   "group": "I",
   "fifaRank": 31,
   "confed": "UEFA",
   "baseRating": 1897.3,
   "preProb": 2.39,
   "marketProb": 2.72
  },
  {
   "code": "ARG",
   "name": "Argentina",
   "flag": "🇦🇷",
   "group": "J",
   "fifaRank": 1,
   "confed": "CONMEBOL",
   "baseRating": 2063.7,
   "preProb": 9.23,
   "marketProb": 8.03
  },
  {
   "code": "ALG",
   "name": "Algeria",
   "flag": "🇩🇿",
   "group": "J",
   "fifaRank": 28,
   "confed": "CAF",
   "baseRating": 1871.8,
   "preProb": 0.39,
   "marketProb": 0.24
  },
  {
   "code": "AUT",
   "name": "Austria",
   "flag": "🇦🇹",
   "group": "J",
   "fifaRank": 24,
   "confed": "UEFA",
   "baseRating": 1894.8,
   "preProb": 0.64,
   "marketProb": 0.56
  },
  {
   "code": "JOR",
   "name": "Jordan",
   "flag": "🇯🇴",
   "group": "J",
   "fifaRank": 63,
   "confed": "AFC",
   "baseRating": 1720.8,
   "preProb": 0.07,
   "marketProb": 0.03
  },
  {
   "code": "POR",
   "name": "Portugal",
   "flag": "🇵🇹",
   "group": "K",
   "fifaRank": 5,
   "confed": "UEFA",
   "baseRating": 2042.0,
   "preProb": 7.94,
   "marketProb": 9.37
  },
  {
   "code": "COD",
   "name": "Congo DR",
   "flag": "🇨🇩",
   "group": "K",
   "fifaRank": 46,
   "confed": "CAF",
   "baseRating": 1792.2,
   "preProb": 0.16,
   "marketProb": 0.09
  },
  {
   "code": "UZB",
   "name": "Uzbekistan",
   "flag": "🇺🇿",
   "group": "K",
   "fifaRank": 50,
   "confed": "AFC",
   "baseRating": 1774.8,
   "preProb": 0.12,
   "marketProb": 0.06
  },
  {
   "code": "COL",
   "name": "Colombia",
   "flag": "🇨🇴",
   "group": "K",
   "fifaRank": 13,
   "confed": "CONMEBOL",
   "baseRating": 1967.4,
   "preProb": 2.24,
   "marketProb": 2.05
  },
  {
   "code": "ENG",
   "name": "England",
   "flag": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
   "group": "L",
   "fifaRank": 4,
   "confed": "UEFA",
   "baseRating": 2056.7,
   "preProb": 10.52,
   "marketProb": 10.54
  },
  {
   "code": "CRO",
   "name": "Croatia",
   "flag": "🇭🇷",
   "group": "L",
   "fifaRank": 11,
   "confed": "UEFA",
   "baseRating": 1961.9,
   "preProb": 1.35,
   "marketProb": 0.93
  },
  {
   "code": "GHA",
   "name": "Ghana",
   "flag": "🇬🇭",
   "group": "L",
   "fifaRank": 73,
   "confed": "CAF",
   "baseRating": 1687.4,
   "preProb": 0.25,
   "marketProb": 0.28
  },
  {
   "code": "PAN",
   "name": "Panama",
   "flag": "🇵🇦",
   "group": "L",
   "fifaRank": 34,
   "confed": "CONCACAF",
   "baseRating": 1841.3,
   "preProb": 0.19,
   "marketProb": 0.08
  }
 ],
 "venues": [
  {
   "id": "BCP",
   "name": "BC Place",
   "fifaName": "BC Place Vancouver",
   "city": "Vancouver",
   "country": "Canada",
   "capacity": 48821,
   "lat": 49.2767,
   "lon": -123.1119,
   "elev": 0
  },
  {
   "id": "TOR",
   "name": "BMO Field",
   "fifaName": "Toronto Stadium",
   "city": "Toronto",
   "country": "Canada",
   "capacity": 44315,
   "lat": 43.6332,
   "lon": -79.4186,
   "elev": 0
  },
  {
   "id": "MEX",
   "name": "Estadio Azteca",
   "fifaName": "Mexico City Stadium",
   "city": "Mexico City",
   "country": "Mexico",
   "capacity": 72766,
   "lat": 19.3029,
   "lon": -99.1505,
   "elev": 0
  },
  {
   "id": "GDL",
   "name": "Estadio Akron",
   "fifaName": "Guadalajara Stadium",
   "city": "Zapopan / Guadalajara",
   "country": "Mexico",
   "capacity": 44330,
   "lat": 20.6818,
   "lon": -103.4627,
   "elev": 0
  },
  {
   "id": "MTY",
   "name": "Estadio BBVA",
   "fifaName": "Monterrey Stadium",
   "city": "Guadalupe / Monterrey",
   "country": "Mexico",
   "capacity": 50113,
   "lat": 25.668,
   "lon": -100.244,
   "elev": 0
  },
  {
   "id": "ATL",
   "name": "Mercedes-Benz Stadium",
   "fifaName": "Atlanta Stadium",
   "city": "Atlanta",
   "country": "United States",
   "capacity": 67382,
   "lat": 33.7554,
   "lon": -84.4008,
   "elev": 0
  },
  {
   "id": "BOS",
   "name": "Gillette Stadium",
   "fifaName": "Boston Stadium",
   "city": "Foxborough / Boston",
   "country": "United States",
   "capacity": 63815,
   "lat": 42.091,
   "lon": -71.2643,
   "elev": 0
  },
  {
   "id": "DAL",
   "name": "AT&T Stadium",
   "fifaName": "Dallas Stadium",
   "city": "Arlington / Dallas",
   "country": "United States",
   "capacity": 70122,
   "lat": 32.7473,
   "lon": -97.0945,
   "elev": 0
  },
  {
   "id": "HOU",
   "name": "NRG Stadium",
   "fifaName": "Houston Stadium",
   "city": "Houston",
   "country": "United States",
   "capacity": 68311,
   "lat": 29.6847,
   "lon": -95.4107,
   "elev": 0
  },
  {
   "id": "KC",
   "name": "Arrowhead Stadium",
   "fifaName": "Kansas City Stadium",
   "city": "Kansas City",
   "country": "United States",
   "capacity": 67513,
   "lat": 39.049,
   "lon": -94.484,
   "elev": 0
  },
  {
   "id": "LA",
   "name": "SoFi Stadium",
   "fifaName": "Los Angeles Stadium",
   "city": "Inglewood / Los Angeles",
   "country": "United States",
   "capacity": 69650,
   "lat": 33.9535,
   "lon": -118.3392,
   "elev": 0
  },
  {
   "id": "MIA",
   "name": "Hard Rock Stadium",
   "fifaName": "Miami Stadium",
   "city": "Miami Gardens / Miami",
   "country": "United States",
   "capacity": 64091,
   "lat": 25.958,
   "lon": -80.2389,
   "elev": 0
  },
  {
   "id": "NYNJ",
   "name": "MetLife Stadium",
   "fifaName": "New York New Jersey Stadium",
   "city": "East Rutherford / New York New Jersey",
   "country": "United States",
   "capacity": 78576,
   "lat": 40.8135,
   "lon": -74.0745,
   "elev": 0
  },
  {
   "id": "PHI",
   "name": "Lincoln Financial Field",
   "fifaName": "Philadelphia Stadium",
   "city": "Philadelphia",
   "country": "United States",
   "capacity": 65827,
   "lat": 39.9008,
   "lon": -75.1675,
   "elev": 0
  },
  {
   "id": "SF",
   "name": "Levi's Stadium",
   "fifaName": "San Francisco Bay Area Stadium",
   "city": "Santa Clara / San Francisco Bay Area",
   "country": "United States",
   "capacity": 69391,
   "lat": 37.403,
   "lon": -121.97,
   "elev": 0
  },
  {
   "id": "SEA",
   "name": "Lumen Field",
   "fifaName": "Seattle Stadium",
   "city": "Seattle",
   "country": "United States",
   "capacity": 65123,
   "lat": 47.5952,
   "lon": -122.3316,
   "elev": 0
  }
 ],
 "matches": [
  {
   "id": "M001",
   "stage": "group",
   "group": "A",
   "dateET": "2026-06-11T15:00:00-04:00",
   "team1": "MEX",
   "team2": "RSA",
   "venueId": "MEX",
   "status": "completed",
   "score": {
    "team1": 2,
    "team2": 0
   }
  },
  {
   "id": "M002",
   "stage": "group",
   "group": "A",
   "dateET": "2026-06-11T22:00:00-04:00",
   "team1": "KOR",
   "team2": "CZE",
   "venueId": "GDL",
   "status": "completed",
   "score": {
    "team1": 2,
    "team2": 1
   }
  },
  {
   "id": "M003",
   "stage": "group",
   "group": "B",
   "dateET": "2026-06-12T15:00:00-04:00",
   "team1": "CAN",
   "team2": "BIH",
   "venueId": "TOR",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M004",
   "stage": "group",
   "group": "D",
   "dateET": "2026-06-12T21:00:00-04:00",
   "team1": "USA",
   "team2": "PAR",
   "venueId": "LA",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M005",
   "stage": "group",
   "group": "B",
   "dateET": "2026-06-13T15:00:00-04:00",
   "team1": "QAT",
   "team2": "SUI",
   "venueId": "SF",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M006",
   "stage": "group",
   "group": "C",
   "dateET": "2026-06-13T18:00:00-04:00",
   "team1": "BRA",
   "team2": "MAR",
   "venueId": "NYNJ",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M007",
   "stage": "group",
   "group": "C",
   "dateET": "2026-06-13T21:00:00-04:00",
   "team1": "HAI",
   "team2": "SCO",
   "venueId": "BOS",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M008",
   "stage": "group",
   "group": "D",
   "dateET": "2026-06-14T00:00:00-04:00",
   "team1": "AUS",
   "team2": "TUR",
   "venueId": "BCP",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M009",
   "stage": "group",
   "group": "E",
   "dateET": "2026-06-14T13:00:00-04:00",
   "team1": "GER",
   "team2": "CUW",
   "venueId": "HOU",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M010",
   "stage": "group",
   "group": "F",
   "dateET": "2026-06-14T16:00:00-04:00",
   "team1": "NED",
   "team2": "JPN",
   "venueId": "DAL",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M011",
   "stage": "group",
   "group": "E",
   "dateET": "2026-06-14T19:00:00-04:00",
   "team1": "CIV",
   "team2": "ECU",
   "venueId": "PHI",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M012",
   "stage": "group",
   "group": "F",
   "dateET": "2026-06-14T22:00:00-04:00",
   "team1": "SWE",
   "team2": "TUN",
   "venueId": "MTY",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M013",
   "stage": "group",
   "group": "H",
   "dateET": "2026-06-15T12:00:00-04:00",
   "team1": "ESP",
   "team2": "CPV",
   "venueId": "ATL",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M014",
   "stage": "group",
   "group": "G",
   "dateET": "2026-06-15T15:00:00-04:00",
   "team1": "BEL",
   "team2": "EGY",
   "venueId": "SEA",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M015",
   "stage": "group",
   "group": "H",
   "dateET": "2026-06-15T18:00:00-04:00",
   "team1": "KSA",
   "team2": "URU",
   "venueId": "MIA",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M016",
   "stage": "group",
   "group": "G",
   "dateET": "2026-06-15T21:00:00-04:00",
   "team1": "IRN",
   "team2": "NZL",
   "venueId": "LA",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M017",
   "stage": "group",
   "group": "I",
   "dateET": "2026-06-16T15:00:00-04:00",
   "team1": "FRA",
   "team2": "SEN",
   "venueId": "NYNJ",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M018",
   "stage": "group",
   "group": "I",
   "dateET": "2026-06-16T18:00:00-04:00",
   "team1": "IRQ",
   "team2": "NOR",
   "venueId": "BOS",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M019",
   "stage": "group",
   "group": "J",
   "dateET": "2026-06-16T21:00:00-04:00",
   "team1": "ARG",
   "team2": "ALG",
   "venueId": "KC",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M020",
   "stage": "group",
   "group": "J",
   "dateET": "2026-06-17T00:00:00-04:00",
   "team1": "AUT",
   "team2": "JOR",
   "venueId": "SF",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M021",
   "stage": "group",
   "group": "K",
   "dateET": "2026-06-17T13:00:00-04:00",
   "team1": "POR",
   "team2": "COD",
   "venueId": "HOU",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M022",
   "stage": "group",
   "group": "L",
   "dateET": "2026-06-17T16:00:00-04:00",
   "team1": "ENG",
   "team2": "CRO",
   "venueId": "DAL",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M023",
   "stage": "group",
   "group": "L",
   "dateET": "2026-06-17T19:00:00-04:00",
   "team1": "GHA",
   "team2": "PAN",
   "venueId": "TOR",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M024",
   "stage": "group",
   "group": "K",
   "dateET": "2026-06-17T22:00:00-04:00",
   "team1": "UZB",
   "team2": "COL",
   "venueId": "MEX",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M025",
   "stage": "group",
   "group": "A",
   "dateET": "2026-06-18T12:00:00-04:00",
   "team1": "CZE",
   "team2": "RSA",
   "venueId": "ATL",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M026",
   "stage": "group",
   "group": "B",
   "dateET": "2026-06-18T15:00:00-04:00",
   "team1": "SUI",
   "team2": "BIH",
   "venueId": "LA",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M027",
   "stage": "group",
   "group": "B",
   "dateET": "2026-06-18T18:00:00-04:00",
   "team1": "CAN",
   "team2": "QAT",
   "venueId": "BCP",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M028",
   "stage": "group",
   "group": "A",
   "dateET": "2026-06-18T21:00:00-04:00",
   "team1": "MEX",
   "team2": "KOR",
   "venueId": "GDL",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M029",
   "stage": "group",
   "group": "D",
   "dateET": "2026-06-19T15:00:00-04:00",
   "team1": "USA",
   "team2": "AUS",
   "venueId": "SEA",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M030",
   "stage": "group",
   "group": "C",
   "dateET": "2026-06-19T18:00:00-04:00",
   "team1": "SCO",
   "team2": "MAR",
   "venueId": "BOS",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M031",
   "stage": "group",
   "group": "C",
   "dateET": "2026-06-19T20:30:00-04:00",
   "team1": "BRA",
   "team2": "HAI",
   "venueId": "PHI",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M032",
   "stage": "group",
   "group": "D",
   "dateET": "2026-06-19T23:00:00-04:00",
   "team1": "TUR",
   "team2": "PAR",
   "venueId": "SF",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M033",
   "stage": "group",
   "group": "F",
   "dateET": "2026-06-20T13:00:00-04:00",
   "team1": "NED",
   "team2": "SWE",
   "venueId": "HOU",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M034",
   "stage": "group",
   "group": "E",
   "dateET": "2026-06-20T16:00:00-04:00",
   "team1": "GER",
   "team2": "CIV",
   "venueId": "TOR",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M035",
   "stage": "group",
   "group": "E",
   "dateET": "2026-06-20T20:00:00-04:00",
   "team1": "ECU",
   "team2": "CUW",
   "venueId": "KC",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M036",
   "stage": "group",
   "group": "F",
   "dateET": "2026-06-21T00:00:00-04:00",
   "team1": "TUN",
   "team2": "JPN",
   "venueId": "MTY",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M037",
   "stage": "group",
   "group": "H",
   "dateET": "2026-06-21T12:00:00-04:00",
   "team1": "ESP",
   "team2": "KSA",
   "venueId": "ATL",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M038",
   "stage": "group",
   "group": "G",
   "dateET": "2026-06-21T15:00:00-04:00",
   "team1": "BEL",
   "team2": "IRN",
   "venueId": "LA",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M039",
   "stage": "group",
   "group": "H",
   "dateET": "2026-06-21T18:00:00-04:00",
   "team1": "URU",
   "team2": "CPV",
   "venueId": "MIA",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M040",
   "stage": "group",
   "group": "G",
   "dateET": "2026-06-21T21:00:00-04:00",
   "team1": "NZL",
   "team2": "EGY",
   "venueId": "BCP",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M041",
   "stage": "group",
   "group": "J",
   "dateET": "2026-06-22T13:00:00-04:00",
   "team1": "ARG",
   "team2": "AUT",
   "venueId": "DAL",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M042",
   "stage": "group",
   "group": "I",
   "dateET": "2026-06-22T17:00:00-04:00",
   "team1": "FRA",
   "team2": "IRQ",
   "venueId": "PHI",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M043",
   "stage": "group",
   "group": "I",
   "dateET": "2026-06-22T20:00:00-04:00",
   "team1": "NOR",
   "team2": "SEN",
   "venueId": "NYNJ",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M044",
   "stage": "group",
   "group": "J",
   "dateET": "2026-06-22T23:00:00-04:00",
   "team1": "JOR",
   "team2": "ALG",
   "venueId": "SF",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M045",
   "stage": "group",
   "group": "K",
   "dateET": "2026-06-23T13:00:00-04:00",
   "team1": "POR",
   "team2": "UZB",
   "venueId": "HOU",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M046",
   "stage": "group",
   "group": "L",
   "dateET": "2026-06-23T16:00:00-04:00",
   "team1": "ENG",
   "team2": "GHA",
   "venueId": "BOS",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M047",
   "stage": "group",
   "group": "L",
   "dateET": "2026-06-23T19:00:00-04:00",
   "team1": "PAN",
   "team2": "CRO",
   "venueId": "TOR",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M048",
   "stage": "group",
   "group": "K",
   "dateET": "2026-06-23T22:00:00-04:00",
   "team1": "COL",
   "team2": "COD",
   "venueId": "GDL",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M049",
   "stage": "group",
   "group": "B",
   "dateET": "2026-06-24T15:00:00-04:00",
   "team1": "SUI",
   "team2": "CAN",
   "venueId": "BCP",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M050",
   "stage": "group",
   "group": "B",
   "dateET": "2026-06-24T15:00:00-04:00",
   "team1": "BIH",
   "team2": "QAT",
   "venueId": "SEA",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M051",
   "stage": "group",
   "group": "C",
   "dateET": "2026-06-24T18:00:00-04:00",
   "team1": "SCO",
   "team2": "BRA",
   "venueId": "MIA",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M052",
   "stage": "group",
   "group": "C",
   "dateET": "2026-06-24T18:00:00-04:00",
   "team1": "MAR",
   "team2": "HAI",
   "venueId": "ATL",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M053",
   "stage": "group",
   "group": "A",
   "dateET": "2026-06-24T21:00:00-04:00",
   "team1": "CZE",
   "team2": "MEX",
   "venueId": "MEX",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M054",
   "stage": "group",
   "group": "A",
   "dateET": "2026-06-24T21:00:00-04:00",
   "team1": "RSA",
   "team2": "KOR",
   "venueId": "MTY",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M055",
   "stage": "group",
   "group": "E",
   "dateET": "2026-06-25T16:00:00-04:00",
   "team1": "ECU",
   "team2": "GER",
   "venueId": "NYNJ",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M056",
   "stage": "group",
   "group": "E",
   "dateET": "2026-06-25T16:00:00-04:00",
   "team1": "CUW",
   "team2": "CIV",
   "venueId": "PHI",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M057",
   "stage": "group",
   "group": "F",
   "dateET": "2026-06-25T19:00:00-04:00",
   "team1": "JPN",
   "team2": "SWE",
   "venueId": "DAL",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M058",
   "stage": "group",
   "group": "F",
   "dateET": "2026-06-25T19:00:00-04:00",
   "team1": "TUN",
   "team2": "NED",
   "venueId": "KC",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M059",
   "stage": "group",
   "group": "D",
   "dateET": "2026-06-25T22:00:00-04:00",
   "team1": "TUR",
   "team2": "USA",
   "venueId": "LA",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M060",
   "stage": "group",
   "group": "D",
   "dateET": "2026-06-25T22:00:00-04:00",
   "team1": "PAR",
   "team2": "AUS",
   "venueId": "SF",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M061",
   "stage": "group",
   "group": "I",
   "dateET": "2026-06-26T15:00:00-04:00",
   "team1": "NOR",
   "team2": "FRA",
   "venueId": "BOS",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M062",
   "stage": "group",
   "group": "I",
   "dateET": "2026-06-26T15:00:00-04:00",
   "team1": "SEN",
   "team2": "IRQ",
   "venueId": "TOR",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M063",
   "stage": "group",
   "group": "H",
   "dateET": "2026-06-26T20:00:00-04:00",
   "team1": "CPV",
   "team2": "KSA",
   "venueId": "HOU",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M064",
   "stage": "group",
   "group": "H",
   "dateET": "2026-06-26T20:00:00-04:00",
   "team1": "URU",
   "team2": "ESP",
   "venueId": "GDL",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M065",
   "stage": "group",
   "group": "G",
   "dateET": "2026-06-26T23:00:00-04:00",
   "team1": "EGY",
   "team2": "IRN",
   "venueId": "SEA",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M066",
   "stage": "group",
   "group": "G",
   "dateET": "2026-06-26T23:00:00-04:00",
   "team1": "NZL",
   "team2": "BEL",
   "venueId": "BCP",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M067",
   "stage": "group",
   "group": "L",
   "dateET": "2026-06-27T17:00:00-04:00",
   "team1": "PAN",
   "team2": "ENG",
   "venueId": "NYNJ",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M068",
   "stage": "group",
   "group": "L",
   "dateET": "2026-06-27T17:00:00-04:00",
   "team1": "CRO",
   "team2": "GHA",
   "venueId": "PHI",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M069",
   "stage": "group",
   "group": "K",
   "dateET": "2026-06-27T19:30:00-04:00",
   "team1": "COL",
   "team2": "POR",
   "venueId": "MIA",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M070",
   "stage": "group",
   "group": "K",
   "dateET": "2026-06-27T19:30:00-04:00",
   "team1": "COD",
   "team2": "UZB",
   "venueId": "ATL",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M071",
   "stage": "group",
   "group": "J",
   "dateET": "2026-06-27T22:00:00-04:00",
   "team1": "ALG",
   "team2": "AUT",
   "venueId": "KC",
   "status": "scheduled",
   "score": null
  },
  {
   "id": "M072",
   "stage": "group",
   "group": "J",
   "dateET": "2026-06-27T22:00:00-04:00",
   "team1": "JOR",
   "team2": "ARG",
   "venueId": "DAL",
   "status": "scheduled",
   "score": null
  }
 ],
 "r32Template": [
  {
   "id": "R32-3",
   "date": "Mon Jun 29",
   "venueId": "BOS",
   "a": {
    "type": "group",
    "group": "E",
    "place": 1
   },
   "b": {
    "type": "third",
    "groups": [
     "A",
     "B",
     "C",
     "D",
     "F"
    ]
   },
   "label": "E1 vs 3rd A/B/C/D/F",
   "matchNo": 74
  },
  {
   "id": "R32-6",
   "date": "Tue Jun 30",
   "venueId": "NYNJ",
   "a": {
    "type": "group",
    "group": "I",
    "place": 1
   },
   "b": {
    "type": "third",
    "groups": [
     "C",
     "D",
     "F",
     "G",
     "H"
    ]
   },
   "label": "I1 vs 3rd C/D/F/G/H",
   "matchNo": 77
  },
  {
   "id": "R32-1",
   "date": "Sun Jun 28",
   "venueId": "LA",
   "a": {
    "type": "group",
    "group": "A",
    "place": 2
   },
   "b": {
    "type": "group",
    "group": "B",
    "place": 2
   },
   "label": "A2 vs B2",
   "matchNo": 73
  },
  {
   "id": "R32-4",
   "date": "Mon Jun 29",
   "venueId": "MTY",
   "a": {
    "type": "group",
    "group": "F",
    "place": 1
   },
   "b": {
    "type": "group",
    "group": "C",
    "place": 2
   },
   "label": "F1 vs C2",
   "matchNo": 75
  },
  {
   "id": "R32-12",
   "date": "Thu Jul 2",
   "venueId": "TOR",
   "a": {
    "type": "group",
    "group": "K",
    "place": 2
   },
   "b": {
    "type": "group",
    "group": "L",
    "place": 2
   },
   "label": "K2 vs L2",
   "matchNo": 83
  },
  {
   "id": "R32-11",
   "date": "Thu Jul 2",
   "venueId": "LA",
   "a": {
    "type": "group",
    "group": "H",
    "place": 1
   },
   "b": {
    "type": "group",
    "group": "J",
    "place": 2
   },
   "label": "H1 vs J2",
   "matchNo": 84
  },
  {
   "id": "R32-10",
   "date": "Wed Jul 1",
   "venueId": "SF",
   "a": {
    "type": "group",
    "group": "D",
    "place": 1
   },
   "b": {
    "type": "third",
    "groups": [
     "B",
     "E",
     "F",
     "I",
     "J"
    ]
   },
   "label": "D1 vs 3rd B/E/F/I/J",
   "matchNo": 81
  },
  {
   "id": "R32-9",
   "date": "Wed Jul 1",
   "venueId": "SEA",
   "a": {
    "type": "group",
    "group": "G",
    "place": 1
   },
   "b": {
    "type": "third",
    "groups": [
     "A",
     "E",
     "H",
     "I",
     "J"
    ]
   },
   "label": "G1 vs 3rd A/E/H/I/J",
   "matchNo": 82
  },
  {
   "id": "R32-2",
   "date": "Mon Jun 29",
   "venueId": "HOU",
   "a": {
    "type": "group",
    "group": "C",
    "place": 1
   },
   "b": {
    "type": "group",
    "group": "F",
    "place": 2
   },
   "label": "C1 vs F2",
   "matchNo": 76
  },
  {
   "id": "R32-5",
   "date": "Tue Jun 30",
   "venueId": "DAL",
   "a": {
    "type": "group",
    "group": "E",
    "place": 2
   },
   "b": {
    "type": "group",
    "group": "I",
    "place": 2
   },
   "label": "E2 vs I2",
   "matchNo": 78
  },
  {
   "id": "R32-7",
   "date": "Tue Jun 30",
   "venueId": "MEX",
   "a": {
    "type": "group",
    "group": "A",
    "place": 1
   },
   "b": {
    "type": "third",
    "groups": [
     "C",
     "E",
     "F",
     "H",
     "I"
    ]
   },
   "label": "A1 vs 3rd C/E/F/H/I",
   "matchNo": 79
  },
  {
   "id": "R32-8",
   "date": "Wed Jul 1",
   "venueId": "ATL",
   "a": {
    "type": "group",
    "group": "L",
    "place": 1
   },
   "b": {
    "type": "third",
    "groups": [
     "E",
     "H",
     "I",
     "J",
     "K"
    ]
   },
   "label": "L1 vs 3rd E/H/I/J/K",
   "matchNo": 80
  },
  {
   "id": "R32-15",
   "date": "Fri Jul 3",
   "venueId": "MIA",
   "a": {
    "type": "group",
    "group": "J",
    "place": 1
   },
   "b": {
    "type": "group",
    "group": "H",
    "place": 2
   },
   "label": "J1 vs H2",
   "matchNo": 86
  },
  {
   "id": "R32-14",
   "date": "Fri Jul 3",
   "venueId": "DAL",
   "a": {
    "type": "group",
    "group": "D",
    "place": 2
   },
   "b": {
    "type": "group",
    "group": "G",
    "place": 2
   },
   "label": "D2 vs G2",
   "matchNo": 88
  },
  {
   "id": "R32-13",
   "date": "Thu Jul 2",
   "venueId": "BCP",
   "a": {
    "type": "group",
    "group": "B",
    "place": 1
   },
   "b": {
    "type": "third",
    "groups": [
     "E",
     "F",
     "G",
     "I",
     "J"
    ]
   },
   "label": "B1 vs 3rd E/F/G/I/J",
   "matchNo": 85
  },
  {
   "id": "R32-16",
   "date": "Fri Jul 3",
   "venueId": "KC",
   "a": {
    "type": "group",
    "group": "K",
    "place": 1
   },
   "b": {
    "type": "third",
    "groups": [
     "D",
     "E",
     "I",
     "J",
     "L"
    ]
   },
   "label": "K1 vs 3rd D/E/I/J/L",
   "matchNo": 87
  }
 ],
 "koSchedule": [
  {
   "round": "Round of 32",
   "date": "Sun Jun 28",
   "venueId": "LA",
   "match": "A runners-up vs B runners-up",
   "timeET": "3:00pm ET"
  },
  {
   "round": "Round of 32",
   "date": "Mon Jun 29",
   "venueId": "HOU",
   "match": "C winners vs F runners-up",
   "timeET": "1:00pm ET"
  },
  {
   "round": "Round of 32",
   "date": "Mon Jun 29",
   "venueId": "BOS",
   "match": "E winners vs third-place qualifier",
   "timeET": "4:30pm ET"
  },
  {
   "round": "Round of 32",
   "date": "Mon Jun 29",
   "venueId": "MTY",
   "match": "F winners vs C runners-up",
   "timeET": "9:00pm ET"
  },
  {
   "round": "Round of 32",
   "date": "Tue Jun 30",
   "venueId": "DAL",
   "match": "E runners-up vs I runners-up",
   "timeET": "1:00pm ET"
  },
  {
   "round": "Round of 32",
   "date": "Tue Jun 30",
   "venueId": "NYNJ",
   "match": "I winners vs third-place qualifier",
   "timeET": "5:00pm ET"
  },
  {
   "round": "Round of 32",
   "date": "Tue Jun 30",
   "venueId": "MEX",
   "match": "A winners vs third-place qualifier",
   "timeET": "9:00pm ET"
  },
  {
   "round": "Round of 32",
   "date": "Wed Jul 1",
   "venueId": "ATL",
   "match": "L winners vs third-place qualifier",
   "timeET": "12:00pm ET"
  },
  {
   "round": "Round of 32",
   "date": "Wed Jul 1",
   "venueId": "SEA",
   "match": "G winners vs third-place qualifier",
   "timeET": "4:00pm ET"
  },
  {
   "round": "Round of 32",
   "date": "Wed Jul 1",
   "venueId": "SF",
   "match": "D winners vs third-place qualifier",
   "timeET": "8:00pm ET"
  },
  {
   "round": "Round of 32",
   "date": "Thu Jul 2",
   "venueId": "LA",
   "match": "H winners vs J runners-up",
   "timeET": "3:00pm ET"
  },
  {
   "round": "Round of 32",
   "date": "Thu Jul 2",
   "venueId": "TOR",
   "match": "K runners-up vs L runners-up",
   "timeET": "7:00pm ET"
  },
  {
   "round": "Round of 32",
   "date": "Thu Jul 2",
   "venueId": "BCP",
   "match": "B winners vs third-place qualifier",
   "timeET": "11:00pm ET"
  },
  {
   "round": "Round of 32",
   "date": "Fri Jul 3",
   "venueId": "DAL",
   "match": "D runners-up vs G runners-up",
   "timeET": "2:00pm ET"
  },
  {
   "round": "Round of 32",
   "date": "Fri Jul 3",
   "venueId": "MIA",
   "match": "J winners vs H runners-up",
   "timeET": "6:00pm ET"
  },
  {
   "round": "Round of 32",
   "date": "Fri Jul 3",
   "venueId": "KC",
   "match": "K winners vs third-place qualifier",
   "timeET": "9:30pm ET"
  },
  {
   "round": "Round of 16",
   "date": "Jul 4-7",
   "venueId": "HOU",
   "match": "Eight Round-of-16 matches across Houston, Philadelphia, NYNJ, Mexico City, Dallas, Seattle, Atlanta and Vancouver",
   "timeET": "various"
  },
  {
   "round": "Quarter-finals",
   "date": "Jul 9-11",
   "venueId": "BOS",
   "match": "Four quarter-finals across Boston, Los Angeles, Miami and Kansas City",
   "timeET": "various"
  },
  {
   "round": "Semi-finals",
   "date": "Jul 14-15",
   "venueId": "DAL",
   "match": "Semi-final 1 in Dallas; Semi-final 2 in Atlanta",
   "timeET": "3:00pm ET / 3:00pm ET"
  },
  {
   "round": "Third-place game",
   "date": "Sat Jul 18",
   "venueId": "MIA",
   "match": "Third-place game",
   "timeET": "5:00pm ET"
  },
  {
   "round": "Final",
   "date": "Sun Jul 19",
   "venueId": "NYNJ",
   "match": "World Cup Final",
   "timeET": "3:00pm ET"
  }
 ],
 "mena": [
  "QAT",
  "MAR",
  "TUN",
  "EGY",
  "IRN",
  "KSA",
  "IRQ",
  "ALG",
  "JOR"
 ],
 "watchlist": [
  {
   "player": "Kylian Mbappé",
   "team": "FRA",
   "note": "Real Madrid"
  },
  {
   "player": "Lionel Messi",
   "team": "ARG",
   "note": "Inter Miami"
  },
  {
   "player": "Jude Bellingham",
   "team": "ENG",
   "note": "Real Madrid"
  },
  {
   "player": "Mohamed Salah",
   "team": "EGY",
   "note": "Liverpool"
  }
 ],
 "league": {
  "entries": [
   {
    "n": "Abdullah Khaled",
    "w": {
     "A": "MEX",
     "B": "CAN",
     "C": "BRA",
     "D": "USA",
     "E": "GER",
     "F": "NED",
     "G": "BEL",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "BRA",
     "FRA"
    ],
    "c": "BRA",
    "locked": "2026-06-12"
   },
   {
    "n": "Fahad Khaled",
    "w": {
     "A": "KOR",
     "B": "SUI",
     "C": "MAR",
     "D": "TUR",
     "E": "GER",
     "F": "NED",
     "G": "EGY",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "POR",
     "NED"
    ],
    "c": "POR",
    "locked": "2026-06-12"
   },
   {
    "n": "Khaled Fahad",
    "w": {
     "A": "MEX",
     "B": "CAN",
     "C": "BRA",
     "D": "USA",
     "E": "GER",
     "F": "NED",
     "G": "BEL",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "CRO"
    },
    "f": [
     "POR",
     "ESP"
    ],
    "c": "ESP",
    "locked": "2026-06-12"
   },
   {
    "n": "Essa",
    "w": {
     "A": "KOR",
     "B": "SUI",
     "C": "BRA",
     "D": "AUS",
     "E": "GER",
     "F": "NED",
     "G": "BEL",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "NED",
     "POR"
    ],
    "c": "NED",
    "locked": "2026-06-12"
   },
   {
    "n": "Wahab Bader",
    "w": {
     "A": "MEX",
     "B": "SUI",
     "C": "BRA",
     "D": "TUR",
     "E": "GER",
     "F": "NED",
     "G": "BEL",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "ARG",
     "ESP"
    ],
    "c": "ARG",
    "locked": "2026-06-12"
   },
   {
    "n": "Nasser Talal",
    "w": {
     "A": "MEX",
     "B": "SUI",
     "C": "BRA",
     "D": "USA",
     "E": "GER",
     "F": "NED",
     "G": "BEL",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "ENG",
     "ESP"
    ],
    "c": "ENG",
    "locked": "2026-06-12"
   },
   {
    "n": "Hmoud Al Sabah",
    "w": {
     "A": "MEX",
     "B": "CAN",
     "C": "BRA",
     "D": "TUR",
     "E": "ECU",
     "F": "NED",
     "G": "BEL",
     "H": "ESP",
     "I": "NOR",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "ESP",
     "POR"
    ],
    "c": "ESP",
    "locked": "2026-06-12"
   },
   {
    "n": "Alibaba",
    "w": {
     "A": "MEX",
     "B": "BIH",
     "C": "MAR",
     "D": "TUR",
     "E": "GER",
     "F": "NED",
     "G": "BEL",
     "H": "KSA",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "KSA",
     "IRN"
    ],
    "c": "IRN",
    "locked": "2026-06-12"
   },
   {
    "n": "Nasser Fahad",
    "w": {
     "A": "MEX",
     "B": "SUI",
     "C": "BRA",
     "D": "TUR",
     "E": "GER",
     "F": "NED",
     "G": "IRN",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "ESP",
     "POR"
    ],
    "c": "ESP",
    "locked": "2026-06-12"
   },
   {
    "n": "Mohammed Jamal",
    "w": {
     "A": "KOR",
     "B": "BIH",
     "C": "BRA",
     "D": "TUR",
     "E": "GER",
     "F": "NED",
     "G": "BEL",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "FRA",
     "ARG"
    ],
    "c": "FRA",
    "locked": "2026-06-12"
   },
   {
    "n": "Salem Athbi",
    "w": {
     "A": "MEX",
     "B": "SUI",
     "C": "BRA",
     "D": "TUR",
     "E": "GER",
     "F": "NED",
     "G": "BEL",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "GER",
     "BRA"
    ],
    "c": "GER",
    "locked": "2026-06-12"
   },
   {
    "n": "Thamer Fares Alnoon",
    "w": {
     "A": "MEX",
     "B": "BIH",
     "C": "BRA",
     "D": "USA",
     "E": "GER",
     "F": "SWE",
     "G": "BEL",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "ESP",
     "BRA"
    ],
    "c": "BRA",
    "locked": "2026-06-12"
   },
   {
    "n": "Ahmed Boareki",
    "w": {
     "A": "MEX",
     "B": "SUI",
     "C": "BRA",
     "D": "PAR",
     "E": "GER",
     "F": "NED",
     "G": "BEL",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "CRO"
    },
    "f": [
     "ARG",
     "FRA"
    ],
    "c": "FRA",
    "locked": "2026-06-12"
   },
   {
    "n": "Mama Aad",
    "w": {
     "A": "MEX",
     "B": "SUI",
     "C": "BRA",
     "D": "TUR",
     "E": "GER",
     "F": "SWE",
     "G": "BEL",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "ESP",
     "POR"
    ],
    "c": "POR",
    "locked": "2026-06-12"
   },
   {
    "n": "Fahad Ali",
    "w": {
     "A": "MEX",
     "B": "SUI",
     "C": "BRA",
     "D": "USA",
     "E": "GER",
     "F": "NED",
     "G": "EGY",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "CRO"
    },
    "f": [
     "NED",
     "POR"
    ],
    "c": "NED",
    "locked": "2026-06-12"
   },
   {
    "n": "Ali Ahmed Hmoud Mohammed",
    "w": {
     "A": "MEX",
     "B": "SUI",
     "C": "BRA",
     "D": "USA",
     "E": "GER",
     "F": "SWE",
     "G": "BEL",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "ESP",
     "ENG"
    ],
    "c": "ESP",
    "locked": "2026-06-12"
   },
   {
    "n": "Eric",
    "w": {
     "A": "MEX",
     "B": "BIH",
     "C": "BRA",
     "D": "TUR",
     "E": "GER",
     "F": "NED",
     "G": "BEL",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "CRO"
    },
    "f": [
     "FRA",
     "ENG"
    ],
    "c": "FRA",
    "locked": "2026-06-12"
   },
   {
    "n": "JMAMS",
    "w": {
     "A": "MEX",
     "B": "SUI",
     "C": "BRA",
     "D": "USA",
     "E": "ECU",
     "F": "NED",
     "G": "BEL",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "ENG",
     "FRA"
    ],
    "c": "ENG",
    "locked": "2026-06-12"
   },
   {
    "n": "Saleh Boareki",
    "w": {
     "A": "KOR",
     "B": "SUI",
     "C": "MAR",
     "D": "TUR",
     "E": "ECU",
     "F": "NED",
     "G": "EGY",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "FRA",
     "ENG"
    ],
    "c": "ENG",
    "locked": "2026-06-12"
   },
   {
    "n": "Faisal Boodai",
    "w": {
     "A": "MEX",
     "B": "SUI",
     "C": "BRA",
     "D": "AUS",
     "E": "GER",
     "F": "NED",
     "G": "BEL",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "CRO"
    },
    "f": [
     "POR",
     "ESP"
    ],
    "c": "POR",
    "locked": "2026-06-12"
   },
   {
    "n": "AMAS",
    "w": {
     "A": "MEX",
     "B": "QAT",
     "C": "MAR",
     "D": "TUR",
     "E": "CIV",
     "F": "TUN",
     "G": "EGY",
     "H": "KSA",
     "I": "SEN",
     "J": "ARG",
     "K": "UZB",
     "L": "GHA"
    },
    "f": [
     "SEN",
     "ARG"
    ],
    "c": "SEN",
    "locked": "2026-06-12"
   },
   {
    "n": "Abdullah Mohammed",
    "w": {
     "A": "MEX",
     "B": "QAT",
     "C": "BRA",
     "D": "TUR",
     "E": "GER",
     "F": "NED",
     "G": "EGY",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "GER",
     "ENG"
    ],
    "c": "ENG",
    "locked": "2026-06-12"
   },
   {
    "n": "Feras Al Qenaei",
    "w": {
     "A": "MEX",
     "B": "SUI",
     "C": "BRA",
     "D": "TUR",
     "E": "GER",
     "F": "NED",
     "G": "BEL",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "ESP",
     "POR"
    ],
    "c": "ESP",
    "locked": "2026-06-12"
   },
   {
    "n": "Moblee",
    "w": {
     "A": "MEX",
     "B": "CAN",
     "C": "BRA",
     "D": "USA",
     "E": "GER",
     "F": "JPN",
     "G": "BEL",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "ESP",
     "BRA"
    ],
    "c": "ESP",
    "locked": "2026-06-12"
   }
  ],
  "scoring": {
   "groupWinner": 2,
   "finalist": 4,
   "champion": 10
  },
  "props": [],
  "propsDeadline": "16 June 2026"
 }
};
if (typeof module !== 'undefined') module.exports = { WC_DATA };
