// Generated by transform.py — do not edit by hand. Patch results here, then rebuild.
const WC_DATA = {
 "meta": {
  "title": "World Cup 2026 — Probability Centre",
  "version": "1.0",
  "asOf": "2026-06-18",
  "asOfNote": "Results through 25 matches, auto-synced from the ESPN public feed 2026-06-18 18:00 UTC. Probabilities recompute in your browser from this data.",
  "sources": [
   {
    "name": "FIFA fixtures and standings",
    "url": "https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026/scores-fixtures"
   },
   {
    "name": "Base ratings: Elo-style ratings derived from FIFA rankings (11 June 2026 snapshot)",
    "url": "https://www.fifa.com/en/ranking/men"
   }
  ],
  "bracketNote": "R32 slots in official bracket order (FIFA match numbers); sequential pairing reproduces the official R16/QF/SF routing to the 19 July MetLife final. Verified against the published knockout schedule, 12 June 2026."
 },
 "teams": [
  {
   "code": "MEX",
   "name": "Mexico",
   "flag": "🇲🇽",
   "group": "A",
   "fifaRank": 14,
   "confed": "CONCACAF",
   "baseRating": 1978.0,
   "preProb": 1.72,
   "marketProb": 1.28
  },
  {
   "code": "RSA",
   "name": "South Africa",
   "flag": "🇿🇦",
   "group": "A",
   "fifaRank": 60,
   "confed": "CAF",
   "baseRating": 1732.4,
   "preProb": 0.06,
   "marketProb": 0.08
  },
  {
   "code": "KOR",
   "name": "Korea Republic",
   "flag": "🇰🇷",
   "group": "A",
   "fifaRank": 25,
   "confed": "AFC",
   "baseRating": 1883.8,
   "preProb": 0.39,
   "marketProb": 0.21
  },
  {
   "code": "CZE",
   "name": "Czechia",
   "flag": "🇨🇿",
   "group": "A",
   "fifaRank": 40,
   "confed": "UEFA",
   "baseRating": 1824.7,
   "preProb": 0.42,
   "marketProb": 0.34
  },
  {
   "code": "CAN",
   "name": "Canada",
   "flag": "🇨🇦",
   "group": "B",
   "fifaRank": 30,
   "confed": "CONCACAF",
   "baseRating": 1890.4,
   "preProb": 0.55,
   "marketProb": 0.42
  },
  {
   "code": "BIH",
   "name": "Bosnia and Herzegovina",
   "flag": "🇧🇦",
   "group": "B",
   "fifaRank": 64,
   "confed": "UEFA",
   "baseRating": 1721.7,
   "preProb": 0.2,
   "marketProb": 0.17
  },
  {
   "code": "QAT",
   "name": "Qatar",
   "flag": "🇶🇦",
   "group": "B",
   "fifaRank": 56,
   "confed": "AFC",
   "baseRating": 1750.8,
   "preProb": 0.12,
   "marketProb": 0.06
  },
  {
   "code": "SUI",
   "name": "Switzerland",
   "flag": "🇨🇭",
   "group": "B",
   "fifaRank": 19,
   "confed": "UEFA",
   "baseRating": 1931.3,
   "preProb": 1.43,
   "marketProb": 1.28
  },
  {
   "code": "BRA",
   "name": "Brazil",
   "flag": "🇧🇷",
   "group": "C",
   "fifaRank": 6,
   "confed": "CONMEBOL",
   "baseRating": 2032.3,
   "preProb": 6.8,
   "marketProb": 8.03
  },
  {
   "code": "MAR",
   "name": "Morocco",
   "flag": "🇲🇦",
   "group": "C",
   "fifaRank": 7,
   "confed": "CAF",
   "baseRating": 1987.0,
   "preProb": 1.92,
   "marketProb": 1.65
  },
  {
   "code": "HAI",
   "name": "Haiti",
   "flag": "🇭🇹",
   "group": "C",
   "fifaRank": 83,
   "confed": "CONCACAF",
   "baseRating": 1640.0,
   "preProb": 0.05,
   "marketProb": 0.03
  },
  {
   "code": "SCO",
   "name": "Scotland",
   "flag": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
   "group": "C",
   "fifaRank": 42,
   "confed": "UEFA",
   "baseRating": 1816.7,
   "preProb": 0.42,
   "marketProb": 0.42
  },
  {
   "code": "USA",
   "name": "United States",
   "flag": "🇺🇸",
   "group": "D",
   "fifaRank": 17,
   "confed": "CONCACAF",
   "baseRating": 1962.7,
   "preProb": 1.51,
   "marketProb": 1.39
  },
  {
   "code": "PAR",
   "name": "Paraguay",
   "flag": "🇵🇾",
   "group": "D",
   "fifaRank": 41,
   "confed": "CONMEBOL",
   "baseRating": 1819.2,
   "preProb": 0.37,
   "marketProb": 0.28
  },
  {
   "code": "AUS",
   "name": "Australia",
   "flag": "🇦🇺",
   "group": "D",
   "fifaRank": 27,
   "confed": "AFC",
   "baseRating": 1872.0,
   "preProb": 0.27,
   "marketProb": 0.14
  },
  {
   "code": "TUR",
   "name": "Türkiye",
   "flag": "🇹🇷",
   "group": "D",
   "fifaRank": 22,
   "confed": "UEFA",
   "baseRating": 1911.9,
   "preProb": 1.04,
   "marketProb": 0.93
  },
  {
   "code": "GER",
   "name": "Germany",
   "flag": "🇩🇪",
   "group": "E",
   "fifaRank": 10,
   "confed": "UEFA",
   "baseRating": 2010.1,
   "preProb": 5.73,
   "marketProb": 5.62
  },
  {
   "code": "CUW",
   "name": "Curaçao",
   "flag": "🇨🇼",
   "group": "E",
   "fifaRank": 82,
   "confed": "CONCACAF",
   "baseRating": 1644.0,
   "preProb": 0.05,
   "marketProb": 0.03
  },
  {
   "code": "CIV",
   "name": "Côte d'Ivoire",
   "flag": "🇨🇮",
   "group": "E",
   "fifaRank": 33,
   "confed": "CAF",
   "baseRating": 1853.6,
   "preProb": 0.45,
   "marketProb": 0.34
  },
  {
   "code": "ECU",
   "name": "Ecuador",
   "flag": "🇪🇨",
   "group": "E",
   "fifaRank": 23,
   "confed": "CONMEBOL",
   "baseRating": 1909.4,
   "preProb": 1.11,
   "marketProb": 1.04
  },
  {
   "code": "NED",
   "name": "Netherlands",
   "flag": "🇳🇱",
   "group": "F",
   "fifaRank": 8,
   "confed": "UEFA",
   "baseRating": 2007.5,
   "preProb": 4.23,
   "marketProb": 4.01
  },
  {
   "code": "JPN",
   "name": "Japan",
   "flag": "🇯🇵",
   "group": "F",
   "fifaRank": 18,
   "confed": "AFC",
   "baseRating": 1935.5,
   "preProb": 1.44,
   "marketProb": 1.5
  },
  {
   "code": "SWE",
   "name": "Sweden",
   "flag": "🇸🇪",
   "group": "F",
   "fifaRank": 38,
   "confed": "UEFA",
   "baseRating": 1840.3,
   "preProb": 0.7,
   "marketProb": 0.7
  },
  {
   "code": "TUN",
   "name": "Tunisia",
   "flag": "🇹🇳",
   "group": "F",
   "fifaRank": 45,
   "confed": "CAF",
   "baseRating": 1799.0,
   "preProb": 0.24,
   "marketProb": 0.16
  },
  {
   "code": "BEL",
   "name": "Belgium",
   "flag": "🇧🇪",
   "group": "G",
   "fifaRank": 9,
   "confed": "UEFA",
   "baseRating": 1986.3,
   "preProb": 2.47,
   "marketProb": 2.06
  },
  {
   "code": "EGY",
   "name": "Egypt",
   "flag": "🇪🇬",
   "group": "G",
   "fifaRank": 29,
   "confed": "CAF",
   "baseRating": 1868.7,
   "preProb": 0.42,
   "marketProb": 0.28
  },
  {
   "code": "IRN",
   "name": "IR Iran",
   "flag": "🇮🇷",
   "group": "G",
   "fifaRank": 20,
   "confed": "AFC",
   "baseRating": 1901.3,
   "preProb": 0.31,
   "marketProb": 0.12
  },
  {
   "code": "NZL",
   "name": "New Zealand",
   "flag": "🇳🇿",
   "group": "G",
   "fifaRank": 85,
   "confed": "OFC",
   "baseRating": 1632.8,
   "preProb": 0.07,
   "marketProb": 0.05
  },
  {
   "code": "ESP",
   "name": "Spain",
   "flag": "🇪🇸",
   "group": "H",
   "fifaRank": 2,
   "confed": "UEFA",
   "baseRating": 2075.3,
   "preProb": 13.83,
   "marketProb": 15.33
  },
  {
   "code": "CPV",
   "name": "Cabo Verde",
   "flag": "🇨🇻",
   "group": "H",
   "fifaRank": 67,
   "confed": "CAF",
   "baseRating": 1706.8,
   "preProb": 0.12,
   "marketProb": 0.08
  },
  {
   "code": "KSA",
   "name": "Saudi Arabia",
   "flag": "🇸🇦",
   "group": "H",
   "fifaRank": 61,
   "confed": "AFC",
   "baseRating": 1731.5,
   "preProb": 0.14,
   "marketProb": 0.09
  },
  {
   "code": "URU",
   "name": "Uruguay",
   "flag": "🇺🇾",
   "group": "H",
   "fifaRank": 16,
   "confed": "CONMEBOL",
   "baseRating": 1944.5,
   "preProb": 1.5,
   "marketProb": 1.28
  },
  {
   "code": "FRA",
   "name": "France",
   "flag": "🇫🇷",
   "group": "I",
   "fifaRank": 3,
   "confed": "UEFA",
   "baseRating": 2069.1,
   "preProb": 13.09,
   "marketProb": 14.66
  },
  {
   "code": "SEN",
   "name": "Senegal",
   "flag": "🇸🇳",
   "group": "I",
   "fifaRank": 15,
   "confed": "CAF",
   "baseRating": 1944.1,
   "preProb": 1.25,
   "marketProb": 0.93
  },
  {
   "code": "IRQ",
   "name": "Iraq",
   "flag": "🇮🇶",
   "group": "I",
   "fifaRank": 57,
   "confed": "AFC",
   "baseRating": 1746.4,
   "preProb": 0.11,
   "marketProb": 0.06
  },
  {
   "code": "NOR",
   "name": "Norway",
   "flag": "🇳🇴",
   "group": "I",
   "fifaRank": 31,
   "confed": "UEFA",
   "baseRating": 1897.3,
   "preProb": 2.39,
   "marketProb": 2.72
  },
  {
   "code": "ARG",
   "name": "Argentina",
   "flag": "🇦🇷",
   "group": "J",
   "fifaRank": 1,
   "confed": "CONMEBOL",
   "baseRating": 2063.7,
   "preProb": 9.23,
   "marketProb": 8.03
  },
  {
   "code": "ALG",
   "name": "Algeria",
   "flag": "🇩🇿",
   "group": "J",
   "fifaRank": 28,
   "confed": "CAF",
   "baseRating": 1871.8,
   "preProb": 0.39,
   "marketProb": 0.24
  },
  {
   "code": "AUT",
   "name": "Austria",
   "flag": "🇦🇹",
   "group": "J",
   "fifaRank": 24,
   "confed": "UEFA",
   "baseRating": 1894.8,
   "preProb": 0.64,
   "marketProb": 0.56
  },
  {
   "code": "JOR",
   "name": "Jordan",
   "flag": "🇯🇴",
   "group": "J",
   "fifaRank": 63,
   "confed": "AFC",
   "baseRating": 1720.8,
   "preProb": 0.07,
   "marketProb": 0.03
  },
  {
   "code": "POR",
   "name": "Portugal",
   "flag": "🇵🇹",
   "group": "K",
   "fifaRank": 5,
   "confed": "UEFA",
   "baseRating": 2042.0,
   "preProb": 7.94,
   "marketProb": 9.37
  },
  {
   "code": "COD",
   "name": "Congo DR",
   "flag": "🇨🇩",
   "group": "K",
   "fifaRank": 46,
   "confed": "CAF",
   "baseRating": 1792.2,
   "preProb": 0.16,
   "marketProb": 0.09
  },
  {
   "code": "UZB",
   "name": "Uzbekistan",
   "flag": "🇺🇿",
   "group": "K",
   "fifaRank": 50,
   "confed": "AFC",
   "baseRating": 1774.8,
   "preProb": 0.12,
   "marketProb": 0.06
  },
  {
   "code": "COL",
   "name": "Colombia",
   "flag": "🇨🇴",
   "group": "K",
   "fifaRank": 13,
   "confed": "CONMEBOL",
   "baseRating": 1967.4,
   "preProb": 2.24,
   "marketProb": 2.05
  },
  {
   "code": "ENG",
   "name": "England",
   "flag": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
   "group": "L",
   "fifaRank": 4,
   "confed": "UEFA",
   "baseRating": 2056.7,
   "preProb": 10.52,
   "marketProb": 10.54
  },
  {
   "code": "CRO",
   "name": "Croatia",
   "flag": "🇭🇷",
   "group": "L",
   "fifaRank": 11,
   "confed": "UEFA",
   "baseRating": 1961.9,
   "preProb": 1.35,
   "marketProb": 0.93
  },
  {
   "code": "GHA",
   "name": "Ghana",
   "flag": "🇬🇭",
   "group": "L",
   "fifaRank": 73,
   "confed": "CAF",
   "baseRating": 1687.4,
   "preProb": 0.25,
   "marketProb": 0.28
  },
  {
   "code": "PAN",
   "name": "Panama",
   "flag": "🇵🇦",
   "group": "L",
   "fifaRank": 34,
   "confed": "CONCACAF",
   "baseRating": 1841.3,
   "preProb": 0.19,
   "marketProb": 0.08
  }
 ],
 "venues": [
  {
   "id": "BCP",
   "name": "BC Place",
   "fifaName": "BC Place Vancouver",
   "city": "Vancouver",
   "country": "Canada",
   "capacity": 48821,
   "lat": 49.2767,
   "lon": -123.1119,
   "elev": 0
  },
  {
   "id": "TOR",
   "name": "BMO Field",
   "fifaName": "Toronto Stadium",
   "city": "Toronto",
   "country": "Canada",
   "capacity": 44315,
   "lat": 43.6332,
   "lon": -79.4186,
   "elev": 0
  },
  {
   "id": "MEX",
   "name": "Estadio Azteca",
   "fifaName": "Mexico City Stadium",
   "city": "Mexico City",
   "country": "Mexico",
   "capacity": 72766,
   "lat": 19.3029,
   "lon": -99.1505,
   "elev": 0
  },
  {
   "id": "GDL",
   "name": "Estadio Akron",
   "fifaName": "Guadalajara Stadium",
   "city": "Zapopan / Guadalajara",
   "country": "Mexico",
   "capacity": 44330,
   "lat": 20.6818,
   "lon": -103.4627,
   "elev": 0
  },
  {
   "id": "MTY",
   "name": "Estadio BBVA",
   "fifaName": "Monterrey Stadium",
   "city": "Guadalupe / Monterrey",
   "country": "Mexico",
   "capacity": 50113,
   "lat": 25.668,
   "lon": -100.244,
   "elev": 0
  },
  {
   "id": "ATL",
   "name": "Mercedes-Benz Stadium",
   "fifaName": "Atlanta Stadium",
   "city": "Atlanta",
   "country": "United States",
   "capacity": 67382,
   "lat": 33.7554,
   "lon": -84.4008,
   "elev": 0
  },
  {
   "id": "BOS",
   "name": "Gillette Stadium",
   "fifaName": "Boston Stadium",
   "city": "Foxborough / Boston",
   "country": "United States",
   "capacity": 63815,
   "lat": 42.091,
   "lon": -71.2643,
   "elev": 0
  },
  {
   "id": "DAL",
   "name": "AT&T Stadium",
   "fifaName": "Dallas Stadium",
   "city": "Arlington / Dallas",
   "country": "United States",
   "capacity": 70122,
   "lat": 32.7473,
   "lon": -97.0945,
   "elev": 0
  },
  {
   "id": "HOU",
   "name": "NRG Stadium",
   "fifaName": "Houston Stadium",
   "city": "Houston",
   "country": "United States",
   "capacity": 68311,
   "lat": 29.6847,
   "lon": -95.4107,
   "elev": 0
  },
  {
   "id": "KC",
   "name": "Arrowhead Stadium",
   "fifaName": "Kansas City Stadium",
   "city": "Kansas City",
   "country": "United States",
   "capacity": 67513,
   "lat": 39.049,
   "lon": -94.484,
   "elev": 0
  },
  {
   "id": "LA",
   "name": "SoFi Stadium",
   "fifaName": "Los Angeles Stadium",
   "city": "Inglewood / Los Angeles",
   "country": "United States",
   "capacity": 69650,
   "lat": 33.9535,
   "lon": -118.3392,
   "elev": 0
  },
  {
   "id": "MIA",
   "name": "Hard Rock Stadium",
   "fifaName": "Miami Stadium",
   "city": "Miami Gardens / Miami",
   "country": "United States",
   "capacity": 64091,
   "lat": 25.958,
   "lon": -80.2389,
   "elev": 0
  },
  {
   "id": "NYNJ",
   "name": "MetLife Stadium",
   "fifaName": "New York New Jersey Stadium",
   "city": "East Rutherford / New York New Jersey",
   "country": "United States",
   "capacity": 78576,
   "lat": 40.8135,
   "lon": -74.0745,
   "elev": 0
  },
  {
   "id": "PHI",
   "name": "Lincoln Financial Field",
   "fifaName": "Philadelphia Stadium",
   "city": "Philadelphia",
   "country": "United States",
   "capacity": 65827,
   "lat": 39.9008,
   "lon": -75.1675,
   "elev": 0
  },
  {
   "id": "SF",
   "name": "Levi's Stadium",
   "fifaName": "San Francisco Bay Area Stadium",
   "city": "Santa Clara / San Francisco Bay Area",
   "country": "United States",
   "capacity": 69391,
   "lat": 37.403,
   "lon": -121.97,
   "elev": 0
  },
  {
   "id": "SEA",
   "name": "Lumen Field",
   "fifaName": "Seattle Stadium",
   "city": "Seattle",
   "country": "United States",
   "capacity": 65123,
   "lat": 47.5952,
   "lon": -122.3316,
   "elev": 0
  }
 ],
 "matches": [
  {
   "id": "M001",
   "stage": "group",
   "group": "A",
   "dateET": "2026-06-11T15:00:00-04:00",
   "team1": "MEX",
   "team2": "RSA",
   "venueId": "MEX",
   "status": "completed",
   "score": {
    "team1": 2,
    "team2": 0
   },
   "market": {
    "h": 0.6776,
    "x": 0.2108,
    "a": 0.1116,
    "book": "Bet365"
   },
   "xg": {
    "team1": 1.35,
    "team2": 0.07
   },
   "goals": [
    {
     "t": "MEX",
     "p": "Julián Quiñones",
     "m": "9'"
    },
    {
     "t": "MEX",
     "p": "Raúl Jiménez",
     "m": "67'"
    }
   ],
   "goals_src": "espn"
  },
  {
   "id": "M002",
   "stage": "group",
   "group": "A",
   "dateET": "2026-06-11T22:00:00-04:00",
   "team1": "KOR",
   "team2": "CZE",
   "venueId": "GDL",
   "status": "completed",
   "score": {
    "team1": 2,
    "team2": 1
   },
   "market": {
    "h": 0.3656,
    "x": 0.3066,
    "a": 0.3278,
    "book": "Bet365"
   },
   "xg": {
    "team1": 1.84,
    "team2": 0.79
   },
   "goals": [
    {
     "t": "CZE",
     "p": "Ladislav Krejcí",
     "m": "59'"
    },
    {
     "t": "KOR",
     "p": "Hwang In-Beom",
     "m": "67'"
    },
    {
     "t": "KOR",
     "p": "Oh Hyeon-Gyu",
     "m": "80'"
    }
   ],
   "goals_src": "espn"
  },
  {
   "id": "M003",
   "stage": "group",
   "group": "B",
   "dateET": "2026-06-12T15:00:00-04:00",
   "team1": "CAN",
   "team2": "BIH",
   "venueId": "TOR",
   "status": "completed",
   "score": {
    "team1": 1,
    "team2": 1
   },
   "market": {
    "h": 0.5282,
    "x": 0.2716,
    "a": 0.2002,
    "book": "Bet365"
   },
   "xg": {
    "team1": 1.27,
    "team2": 1.02
   },
   "goals": [
    {
     "t": "BIH",
     "p": "Jovo Lukic",
     "m": "21'"
    },
    {
     "t": "CAN",
     "p": "Cyle Larin",
     "m": "78'"
    }
   ],
   "goals_src": "espn"
  },
  {
   "id": "M004",
   "stage": "group",
   "group": "D",
   "dateET": "2026-06-12T21:00:00-04:00",
   "team1": "USA",
   "team2": "PAR",
   "venueId": "LA",
   "status": "completed",
   "score": {
    "team1": 4,
    "team2": 1
   },
   "market": {
    "h": 0.4628,
    "x": 0.2875,
    "a": 0.2497,
    "book": "Bet365"
   },
   "xg": {
    "team1": 1.44,
    "team2": 0.46
   },
   "goals": [
    {
     "t": "USA",
     "p": "Damián Bobadilla",
     "m": "7'",
     "og": true
    },
    {
     "t": "USA",
     "p": "Folarin Balogun",
     "m": "31'"
    },
    {
     "t": "USA",
     "p": "Folarin Balogun",
     "m": "45'+5'"
    },
    {
     "t": "PAR",
     "p": "Maurício",
     "m": "73'"
    },
    {
     "t": "USA",
     "p": "Giovanni Reyna",
     "m": "90'+8'"
    }
   ],
   "goals_src": "espn"
  },
  {
   "id": "M005",
   "stage": "group",
   "group": "B",
   "dateET": "2026-06-13T15:00:00-04:00",
   "team1": "QAT",
   "team2": "SUI",
   "venueId": "SF",
   "status": "completed",
   "score": {
    "team1": 1,
    "team2": 1
   },
   "market": {
    "h": 0.0636,
    "x": 0.1273,
    "a": 0.8091,
    "book": "Bet365"
   },
   "xg": {
    "team1": 0.75,
    "team2": 3.3
   },
   "goals": [
    {
     "t": "SUI",
     "p": "Breel Embolo",
     "m": "17'",
     "pen": true
    },
    {
     "t": "QAT",
     "p": "Miro Muheim",
     "m": "90'+4'",
     "og": true
    }
   ],
   "goals_src": "espn"
  },
  {
   "id": "M006",
   "stage": "group",
   "group": "C",
   "dateET": "2026-06-13T18:00:00-04:00",
   "team1": "BRA",
   "team2": "MAR",
   "venueId": "NYNJ",
   "status": "completed",
   "score": {
    "team1": 1,
    "team2": 1
   },
   "market": {
    "h": 0.5766,
    "x": 0.2504,
    "a": 0.173,
    "book": "Bet365"
   },
   "xg": {
    "team1": 1.24,
    "team2": 1.56
   },
   "goals": [
    {
     "t": "MAR",
     "p": "Ismael Saibari",
     "m": "21'"
    },
    {
     "t": "BRA",
     "p": "Vinícius Júnior",
     "m": "32'"
    }
   ],
   "goals_src": "espn"
  },
  {
   "id": "M007",
   "stage": "group",
   "group": "C",
   "dateET": "2026-06-13T21:00:00-04:00",
   "team1": "HAI",
   "team2": "SCO",
   "venueId": "BOS",
   "status": "completed",
   "score": {
    "team1": 0,
    "team2": 1
   },
   "market": {
    "h": 0.1579,
    "x": 0.2105,
    "a": 0.6316,
    "book": "Bet365"
   },
   "xg": {
    "team1": 1.24,
    "team2": 1.16
   },
   "goals": [
    {
     "t": "SCO",
     "p": "John McGinn",
     "m": "28'"
    }
   ],
   "goals_src": "espn"
  },
  {
   "id": "M008",
   "stage": "group",
   "group": "D",
   "dateET": "2026-06-14T00:00:00-04:00",
   "team1": "AUS",
   "team2": "TUR",
   "venueId": "BCP",
   "status": "completed",
   "score": {
    "team1": 2,
    "team2": 0
   },
   "market": {
    "h": 0.1816,
    "x": 0.2577,
    "a": 0.5608,
    "book": "Bet365"
   },
   "xg": {
    "team1": 0.75,
    "team2": 1.3
   },
   "goals": [
    {
     "t": "AUS",
     "p": "Nestory Irankunda",
     "m": "27'"
    },
    {
     "t": "AUS",
     "p": "Connor Metcalfe",
     "m": "75'"
    }
   ],
   "goals_src": "espn"
  },
  {
   "id": "M009",
   "stage": "group",
   "group": "E",
   "dateET": "2026-06-14T13:00:00-04:00",
   "team1": "GER",
   "team2": "CUW",
   "venueId": "HOU",
   "status": "completed",
   "score": {
    "team1": 7,
    "team2": 1
   },
   "market": {
    "h": 0.9115,
    "x": 0.0558,
    "a": 0.0327,
    "book": "Bet365"
   },
   "xg": {
    "team1": 3.93,
    "team2": 0.4
   },
   "goals": [
    {
     "t": "GER",
     "p": "Felix Nmecha",
     "m": "6'"
    },
    {
     "t": "CUW",
     "p": "Livano Comenencia",
     "m": "21'"
    },
    {
     "t": "GER",
     "p": "Nico Schlotterbeck",
     "m": "38'"
    },
    {
     "t": "GER",
     "p": "Kai Havertz",
     "m": "45'+5'",
     "pen": true
    },
    {
     "t": "GER",
     "p": "Jamal Musiala",
     "m": "47'"
    },
    {
     "t": "GER",
     "p": "Nathaniel Brown",
     "m": "68'"
    },
    {
     "t": "GER",
     "p": "Deniz Undav",
     "m": "78'"
    },
    {
     "t": "GER",
     "p": "Kai Havertz",
     "m": "88'"
    }
   ],
   "goals_src": "espn"
  },
  {
   "id": "M010",
   "stage": "group",
   "group": "F",
   "dateET": "2026-06-14T16:00:00-04:00",
   "team1": "NED",
   "team2": "JPN",
   "venueId": "DAL",
   "status": "completed",
   "score": {
    "team1": 2,
    "team2": 2
   },
   "market": {
    "h": 0.4713,
    "x": 0.2773,
    "a": 0.2514,
    "book": "Bet365"
   },
   "xg": {
    "team1": 0.75,
    "team2": 0.53
   },
   "goals": [
    {
     "t": "NED",
     "p": "Virgil van Dijk",
     "m": "51'"
    },
    {
     "t": "JPN",
     "p": "Keito Nakamura",
     "m": "57'"
    },
    {
     "t": "NED",
     "p": "Crysencio Summerville",
     "m": "64'"
    },
    {
     "t": "JPN",
     "p": "Daichi Kamada",
     "m": "89'"
    }
   ],
   "goals_src": "espn"
  },
  {
   "id": "M011",
   "stage": "group",
   "group": "E",
   "dateET": "2026-06-14T19:00:00-04:00",
   "team1": "CIV",
   "team2": "ECU",
   "venueId": "PHI",
   "status": "completed",
   "score": {
    "team1": 1,
    "team2": 0
   },
   "market": {
    "h": 0.2802,
    "x": 0.3308,
    "a": 0.3889,
    "book": "Bet365"
   },
   "xg": {
    "team1": 1.7,
    "team2": 0.99
   },
   "goals": [
    {
     "t": "CIV",
     "p": "Amad Diallo",
     "m": "90'"
    }
   ],
   "goals_src": "espn"
  },
  {
   "id": "M012",
   "stage": "group",
   "group": "F",
   "dateET": "2026-06-14T22:00:00-04:00",
   "team1": "SWE",
   "team2": "TUN",
   "venueId": "MTY",
   "status": "completed",
   "score": {
    "team1": 5,
    "team2": 1
   },
   "market": {
    "h": 0.5224,
    "x": 0.2687,
    "a": 0.209,
    "book": "Bet365"
   },
   "xg": {
    "team1": 1.34,
    "team2": 0.29
   },
   "goals": [
    {
     "t": "SWE",
     "p": "Yasin Ayari",
     "m": "7'"
    },
    {
     "t": "SWE",
     "p": "Alexander Isak",
     "m": "30'"
    },
    {
     "t": "TUN",
     "p": "Omar Rekik",
     "m": "43'"
    },
    {
     "t": "SWE",
     "p": "Viktor Gyökeres",
     "m": "59'"
    },
    {
     "t": "SWE",
     "p": "Mattias Svanberg",
     "m": "84'"
    },
    {
     "t": "SWE",
     "p": "Yasin Ayari",
     "m": "90'+6'"
    }
   ],
   "goals_src": "espn"
  },
  {
   "id": "M013",
   "stage": "group",
   "group": "H",
   "dateET": "2026-06-15T12:00:00-04:00",
   "team1": "ESP",
   "team2": "CPV",
   "venueId": "ATL",
   "status": "completed",
   "score": {
    "team1": 0,
    "team2": 0
   },
   "market": {
    "h": 0.8955,
    "x": 0.0633,
    "a": 0.0413,
    "book": "Bet365"
   },
   "goals": [],
   "goals_src": "espn",
   "xg": {
    "team1": 2.31,
    "team2": 0.3
   }
  },
  {
   "id": "M014",
   "stage": "group",
   "group": "G",
   "dateET": "2026-06-15T15:00:00-04:00",
   "team1": "BEL",
   "team2": "EGY",
   "venueId": "SEA",
   "status": "completed",
   "score": {
    "team1": 1,
    "team2": 1
   },
   "market": {
    "h": 0.6251,
    "x": 0.2277,
    "a": 0.1471,
    "book": "Bet365"
   },
   "goals": [
    {
     "t": "EGY",
     "p": "Emam Ashour",
     "m": "19'"
    },
    {
     "t": "BEL",
     "p": "Mohamed Hany",
     "m": "66'",
     "og": true
    }
   ],
   "goals_src": "espn",
   "xg": {
    "team1": 1.42,
    "team2": 1.08
   }
  },
  {
   "id": "M015",
   "stage": "group",
   "group": "H",
   "dateET": "2026-06-15T18:00:00-04:00",
   "team1": "KSA",
   "team2": "URU",
   "venueId": "MIA",
   "status": "completed",
   "score": {
    "team1": 1,
    "team2": 1
   },
   "market": {
    "h": 0.1257,
    "x": 0.2244,
    "a": 0.65,
    "book": "Bet365"
   },
   "goals": [
    {
     "t": "KSA",
     "p": "Abdulelah Al-Amri",
     "m": "41'"
    },
    {
     "t": "URU",
     "p": "Maxi Araújo",
     "m": "80'"
    }
   ],
   "goals_src": "espn",
   "xg": {
    "team1": 1.1,
    "team2": 1.6
   }
  },
  {
   "id": "M016",
   "stage": "group",
   "group": "G",
   "dateET": "2026-06-15T21:00:00-04:00",
   "team1": "IRN",
   "team2": "NZL",
   "venueId": "LA",
   "status": "completed",
   "score": {
    "team1": 2,
    "team2": 2
   },
   "market": {
    "h": 0.5224,
    "x": 0.2687,
    "a": 0.209,
    "book": "Bet365"
   },
   "goals": [
    {
     "t": "NZL",
     "p": "Elijah Just",
     "m": "7'"
    },
    {
     "t": "IRN",
     "p": "Ramin Rezaeian",
     "m": "32'"
    },
    {
     "t": "NZL",
     "p": "Elijah Just",
     "m": "54'"
    },
    {
     "t": "IRN",
     "p": "Mohammad Mohebbi",
     "m": "64'"
    }
   ],
   "goals_src": "espn",
   "xg": {
    "team1": 1.43,
    "team2": 1.23
   }
  },
  {
   "id": "M017",
   "stage": "group",
   "group": "I",
   "dateET": "2026-06-16T15:00:00-04:00",
   "team1": "FRA",
   "team2": "SEN",
   "venueId": "NYNJ",
   "status": "completed",
   "score": {
    "team1": 3,
    "team2": 1
   },
   "market": {
    "h": 0.6569,
    "x": 0.2071,
    "a": 0.1361,
    "book": "Bet365"
   },
   "goals": [
    {
     "t": "FRA",
     "p": "Kylian Mbappé",
     "m": "66'"
    },
    {
     "t": "FRA",
     "p": "Bradley Barcola",
     "m": "82'"
    },
    {
     "t": "SEN",
     "p": "Ibrahim Mbaye",
     "m": "90'+5'"
    },
    {
     "t": "FRA",
     "p": "Kylian Mbappé",
     "m": "90'+6'"
    }
   ],
   "goals_src": "espn",
   "xg": {
    "team1": 1.94,
    "team2": 0.51
   }
  },
  {
   "id": "M018",
   "stage": "group",
   "group": "I",
   "dateET": "2026-06-16T18:00:00-04:00",
   "team1": "IRQ",
   "team2": "NOR",
   "venueId": "BOS",
   "status": "completed",
   "score": {
    "team1": 1,
    "team2": 4
   },
   "market": {
    "h": 0.0789,
    "x": 0.1456,
    "a": 0.7756,
    "book": "Bet365"
   },
   "goals": [
    {
     "t": "NOR",
     "p": "Erling Haaland",
     "m": "29'"
    },
    {
     "t": "IRQ",
     "p": "Aymen Hussein",
     "m": "39'"
    },
    {
     "t": "NOR",
     "p": "Erling Haaland",
     "m": "43'"
    },
    {
     "t": "NOR",
     "p": "Leo Østigard",
     "m": "76'"
    },
    {
     "t": "NOR",
     "p": "Aymen Hussein",
     "m": "90'+6'",
     "og": true
    }
   ],
   "goals_src": "espn",
   "xg": {
    "team1": 0.76,
    "team2": 3.01
   }
  },
  {
   "id": "M019",
   "stage": "group",
   "group": "J",
   "dateET": "2026-06-16T21:00:00-04:00",
   "team1": "ARG",
   "team2": "ALG",
   "venueId": "KC",
   "status": "completed",
   "score": {
    "team1": 3,
    "team2": 0
   },
   "market": {
    "h": 0.6364,
    "x": 0.2273,
    "a": 0.1364,
    "book": "Bet365"
   },
   "goals": [
    {
     "t": "ARG",
     "p": "Lionel Messi",
     "m": "17'"
    },
    {
     "t": "ARG",
     "p": "Lionel Messi",
     "m": "60'"
    },
    {
     "t": "ARG",
     "p": "Lionel Messi",
     "m": "76'"
    }
   ],
   "goals_src": "espn",
   "xg": {
    "team1": 1.25,
    "team2": 0.33
   }
  },
  {
   "id": "M020",
   "stage": "group",
   "group": "J",
   "dateET": "2026-06-17T00:00:00-04:00",
   "team1": "AUT",
   "team2": "JOR",
   "venueId": "SF",
   "status": "completed",
   "score": {
    "team1": 3,
    "team2": 1
   },
   "market": {
    "h": 0.6883,
    "x": 0.2,
    "a": 0.1117,
    "book": "Bet365"
   },
   "goals": [
    {
     "t": "AUT",
     "p": "Romano Schmid",
     "m": "21'"
    },
    {
     "t": "JOR",
     "p": "Ali Olwan",
     "m": "50'"
    },
    {
     "t": "AUT",
     "p": "Yazan Al-Arab",
     "m": "76'",
     "og": true
    },
    {
     "t": "AUT",
     "p": "Marko Arnautovic",
     "m": "90'+12'",
     "pen": true
    }
   ],
   "goals_src": "espn",
   "xg": {
    "team1": 1.79,
    "team2": 0.56
   }
  },
  {
   "id": "M021",
   "stage": "group",
   "group": "K",
   "dateET": "2026-06-17T13:00:00-04:00",
   "team1": "POR",
   "team2": "COD",
   "venueId": "HOU",
   "status": "completed",
   "score": {
    "team1": 1,
    "team2": 1
   },
   "market": {
    "h": 0.7337,
    "x": 0.1803,
    "a": 0.086,
    "book": "Bet365"
   },
   "goals": [
    {
     "t": "POR",
     "p": "João Neves",
     "m": "6'"
    },
    {
     "t": "COD",
     "p": "Yoane Wissa",
     "m": "45'+5'"
    }
   ],
   "goals_src": "espn",
   "xg": {
    "team1": 0.7,
    "team2": 0.8
   }
  },
  {
   "id": "M022",
   "stage": "group",
   "group": "L",
   "dateET": "2026-06-17T16:00:00-04:00",
   "team1": "ENG",
   "team2": "CRO",
   "venueId": "DAL",
   "status": "completed",
   "score": {
    "team1": 4,
    "team2": 2
   },
   "market": {
    "h": 0.5726,
    "x": 0.2452,
    "a": 0.1822,
    "book": "Bet365"
   },
   "goals": [
    {
     "t": "ENG",
     "p": "Harry Kane",
     "m": "12'",
     "pen": true
    },
    {
     "t": "CRO",
     "p": "Martin Baturina",
     "m": "36'"
    },
    {
     "t": "ENG",
     "p": "Harry Kane",
     "m": "42'"
    },
    {
     "t": "CRO",
     "p": "Petar Musa",
     "m": "45'+5'"
    },
    {
     "t": "ENG",
     "p": "Jude Bellingham",
     "m": "47'"
    },
    {
     "t": "ENG",
     "p": "Marcus Rashford",
     "m": "85'"
    }
   ],
   "goals_src": "espn",
   "xg": {
    "team1": 2.88,
    "team2": 0.7
   }
  },
  {
   "id": "M023",
   "stage": "group",
   "group": "L",
   "dateET": "2026-06-17T19:00:00-04:00",
   "team1": "GHA",
   "team2": "PAN",
   "venueId": "TOR",
   "status": "completed",
   "score": {
    "team1": 1,
    "team2": 0
   },
   "market": {
    "h": 0.4012,
    "x": 0.2946,
    "a": 0.3041,
    "book": "Bet365"
   },
   "goals": [
    {
     "t": "GHA",
     "p": "Caleb Yirenkyi",
     "m": "90'+5'"
    }
   ],
   "goals_src": "espn",
   "xg": {
    "team1": 1.31,
    "team2": 0.74
   }
  },
  {
   "id": "M024",
   "stage": "group",
   "group": "K",
   "dateET": "2026-06-17T22:00:00-04:00",
   "team1": "UZB",
   "team2": "COL",
   "venueId": "MEX",
   "status": "completed",
   "score": {
    "team1": 1,
    "team2": 3
   },
   "market": {
    "h": 0.0951,
    "x": 0.1901,
    "a": 0.7148,
    "book": "Bet365"
   },
   "goals": [
    {
     "t": "COL",
     "p": "Daniel Muñoz",
     "m": "40'"
    },
    {
     "t": "UZB",
     "p": "Abbosbek Fayzullaev",
     "m": "60'"
    },
    {
     "t": "COL",
     "p": "Luis Díaz",
     "m": "65'"
    },
    {
     "t": "COL",
     "p": "Jáminton Campaz",
     "m": "90'+9'"
    }
   ],
   "goals_src": "espn",
   "xg": {
    "team1": 1.24,
    "team2": 1.57
   }
  },
  {
   "id": "M025",
   "stage": "group",
   "group": "A",
   "dateET": "2026-06-18T12:00:00-04:00",
   "team1": "CZE",
   "team2": "RSA",
   "venueId": "ATL",
   "status": "completed",
   "score": {
    "team1": 1,
    "team2": 1
   },
   "market": {
    "h": 0.5179,
    "x": 0.2633,
    "a": 0.2189,
    "book": "Bet365"
   },
   "goals": [
    {
     "t": "CZE",
     "p": "Michal Sadílek",
     "m": "6'"
    },
    {
     "t": "RSA",
     "p": "Teboho Mokoena",
     "m": "83'",
     "pen": true
    }
   ],
   "goals_src": "espn"
  },
  {
   "id": "M026",
   "stage": "group",
   "group": "B",
   "dateET": "2026-06-18T15:00:00-04:00",
   "team1": "SUI",
   "team2": "BIH",
   "venueId": "LA",
   "status": "scheduled",
   "score": null,
   "market": {
    "h": 0.6145,
    "x": 0.2268,
    "a": 0.1587,
    "book": "Bet365"
   }
  },
  {
   "id": "M027",
   "stage": "group",
   "group": "B",
   "dateET": "2026-06-18T18:00:00-04:00",
   "team1": "CAN",
   "team2": "QAT",
   "venueId": "BCP",
   "status": "scheduled",
   "score": null,
   "market": {
    "h": 0.7319,
    "x": 0.173,
    "a": 0.0951,
    "book": "Bet365"
   }
  },
  {
   "id": "M028",
   "stage": "group",
   "group": "A",
   "dateET": "2026-06-18T21:00:00-04:00",
   "team1": "MEX",
   "team2": "KOR",
   "venueId": "GDL",
   "status": "scheduled",
   "score": null,
   "market": {
    "h": 0.4628,
    "x": 0.2875,
    "a": 0.2497,
    "book": "Bet365"
   }
  },
  {
   "id": "M029",
   "stage": "group",
   "group": "D",
   "dateET": "2026-06-19T15:00:00-04:00",
   "team1": "USA",
   "team2": "AUS",
   "venueId": "SEA",
   "status": "scheduled",
   "score": null,
   "market": {
    "h": 0.5919,
    "x": 0.2187,
    "a": 0.1894,
    "book": "Bet365"
   }
  },
  {
   "id": "M030",
   "stage": "group",
   "group": "C",
   "dateET": "2026-06-19T18:00:00-04:00",
   "team1": "SCO",
   "team2": "MAR",
   "venueId": "BOS",
   "status": "scheduled",
   "score": null,
   "market": {
    "h": 0.1894,
    "x": 0.2631,
    "a": 0.5475,
    "book": "Bet365"
   }
  },
  {
   "id": "M031",
   "stage": "group",
   "group": "C",
   "dateET": "2026-06-19T20:30:00-04:00",
   "team1": "BRA",
   "team2": "HAI",
   "venueId": "PHI",
   "status": "scheduled",
   "score": null,
   "market": {
    "h": 0.8722,
    "x": 0.0864,
    "a": 0.0413,
    "book": "Bet365"
   }
  },
  {
   "id": "M032",
   "stage": "group",
   "group": "D",
   "dateET": "2026-06-19T23:00:00-04:00",
   "team1": "TUR",
   "team2": "PAR",
   "venueId": "SF",
   "status": "scheduled",
   "score": null,
   "market": {
    "h": 0.4727,
    "x": 0.2909,
    "a": 0.2364,
    "book": "Bet365"
   }
  },
  {
   "id": "M033",
   "stage": "group",
   "group": "F",
   "dateET": "2026-06-20T13:00:00-04:00",
   "team1": "NED",
   "team2": "SWE",
   "venueId": "HOU",
   "status": "scheduled",
   "score": null,
   "market": {
    "h": 0.5496,
    "x": 0.2502,
    "a": 0.2002,
    "book": "Bet365"
   }
  },
  {
   "id": "M034",
   "stage": "group",
   "group": "E",
   "dateET": "2026-06-20T16:00:00-04:00",
   "team1": "GER",
   "team2": "CIV",
   "venueId": "TOR",
   "status": "scheduled",
   "score": null,
   "market": {
    "h": 0.6103,
    "x": 0.2252,
    "a": 0.1645,
    "book": "Bet365"
   }
  },
  {
   "id": "M035",
   "stage": "group",
   "group": "E",
   "dateET": "2026-06-20T20:00:00-04:00",
   "team1": "ECU",
   "team2": "CUW",
   "venueId": "KC",
   "status": "scheduled",
   "score": null,
   "market": {
    "h": 0.8688,
    "x": 0.0861,
    "a": 0.0451,
    "book": "Bet365"
   }
  },
  {
   "id": "M036",
   "stage": "group",
   "group": "F",
   "dateET": "2026-06-21T00:00:00-04:00",
   "team1": "TUN",
   "team2": "JPN",
   "venueId": "MTY",
   "status": "scheduled",
   "score": null,
   "market": {
    "h": 0.1455,
    "x": 0.2364,
    "a": 0.6181,
    "book": "Bet365"
   }
  },
  {
   "id": "M037",
   "stage": "group",
   "group": "H",
   "dateET": "2026-06-21T12:00:00-04:00",
   "team1": "ESP",
   "team2": "KSA",
   "venueId": "ATL",
   "status": "scheduled",
   "score": null,
   "market": {
    "h": 0.8603,
    "x": 0.0946,
    "a": 0.0451,
    "book": "Bet365"
   }
  },
  {
   "id": "M038",
   "stage": "group",
   "group": "G",
   "dateET": "2026-06-21T15:00:00-04:00",
   "team1": "BEL",
   "team2": "IRN",
   "venueId": "LA",
   "status": "scheduled",
   "score": null,
   "market": {
    "h": 0.6645,
    "x": 0.2097,
    "a": 0.1258,
    "book": "Bet365"
   }
  },
  {
   "id": "M039",
   "stage": "group",
   "group": "H",
   "dateET": "2026-06-21T18:00:00-04:00",
   "team1": "URU",
   "team2": "CPV",
   "venueId": "MIA",
   "status": "scheduled",
   "score": null,
   "market": {
    "h": 0.6292,
    "x": 0.236,
    "a": 0.1348,
    "book": "Bet365"
   }
  },
  {
   "id": "M040",
   "stage": "group",
   "group": "G",
   "dateET": "2026-06-21T21:00:00-04:00",
   "team1": "NZL",
   "team2": "EGY",
   "venueId": "BCP",
   "status": "scheduled",
   "score": null,
   "market": {
    "h": 0.172,
    "x": 0.2366,
    "a": 0.5914,
    "book": "Bet365"
   }
  },
  {
   "id": "M041",
   "stage": "group",
   "group": "J",
   "dateET": "2026-06-22T13:00:00-04:00",
   "team1": "ARG",
   "team2": "AUT",
   "venueId": "DAL",
   "status": "scheduled",
   "score": null,
   "market": {
    "h": 0.6045,
    "x": 0.2373,
    "a": 0.1582,
    "book": "Bet365"
   }
  },
  {
   "id": "M042",
   "stage": "group",
   "group": "I",
   "dateET": "2026-06-22T17:00:00-04:00",
   "team1": "FRA",
   "team2": "IRQ",
   "venueId": "PHI",
   "status": "scheduled",
   "score": null,
   "market": {
    "h": 0.8774,
    "x": 0.0948,
    "a": 0.0279,
    "book": "Bet365"
   }
  },
  {
   "id": "M043",
   "stage": "group",
   "group": "I",
   "dateET": "2026-06-22T20:00:00-04:00",
   "team1": "NOR",
   "team2": "SEN",
   "venueId": "NYNJ",
   "status": "scheduled",
   "score": null,
   "market": {
    "h": 0.4135,
    "x": 0.2797,
    "a": 0.3068,
    "book": "Bet365"
   }
  },
  {
   "id": "M044",
   "stage": "group",
   "group": "J",
   "dateET": "2026-06-22T23:00:00-04:00",
   "team1": "JOR",
   "team2": "ALG",
   "venueId": "SF",
   "status": "scheduled",
   "score": null,
   "market": {
    "h": 0.1582,
    "x": 0.2373,
    "a": 0.6045,
    "book": "Bet365"
   }
  },
  {
   "id": "M045",
   "stage": "group",
   "group": "K",
   "dateET": "2026-06-23T13:00:00-04:00",
   "team1": "POR",
   "team2": "UZB",
   "venueId": "HOU",
   "status": "scheduled",
   "score": null,
   "market": {
    "h": 0.7913,
    "x": 0.1357,
    "a": 0.073,
    "book": "Bet365"
   }
  },
  {
   "id": "M046",
   "stage": "group",
   "group": "L",
   "dateET": "2026-06-23T16:00:00-04:00",
   "team1": "ENG",
   "team2": "GHA",
   "venueId": "BOS",
   "status": "scheduled",
   "score": null,
   "market": {
    "h": 0.7758,
    "x": 0.1514,
    "a": 0.0728,
    "book": "Bet365"
   }
  },
  {
   "id": "M047",
   "stage": "group",
   "group": "L",
   "dateET": "2026-06-23T19:00:00-04:00",
   "team1": "PAN",
   "team2": "CRO",
   "venueId": "TOR",
   "status": "scheduled",
   "score": null,
   "market": {
    "h": 0.1455,
    "x": 0.2364,
    "a": 0.6181,
    "book": "Bet365"
   }
  },
  {
   "id": "M048",
   "stage": "group",
   "group": "K",
   "dateET": "2026-06-23T22:00:00-04:00",
   "team1": "COL",
   "team2": "COD",
   "venueId": "GDL",
   "status": "scheduled",
   "score": null,
   "market": {
    "h": 0.6438,
    "x": 0.2201,
    "a": 0.1361,
    "book": "Bet365"
   }
  },
  {
   "id": "M049",
   "stage": "group",
   "group": "B",
   "dateET": "2026-06-24T15:00:00-04:00",
   "team1": "SUI",
   "team2": "CAN",
   "venueId": "BCP",
   "status": "scheduled",
   "score": null,
   "market": {
    "h": 0.4472,
    "x": 0.2846,
    "a": 0.2683,
    "book": "Bet365"
   }
  },
  {
   "id": "M050",
   "stage": "group",
   "group": "B",
   "dateET": "2026-06-24T15:00:00-04:00",
   "team1": "BIH",
   "team2": "QAT",
   "venueId": "SEA",
   "status": "scheduled",
   "score": null,
   "market": {
    "h": 0.5906,
    "x": 0.252,
    "a": 0.1575,
    "book": "Bet365"
   }
  },
  {
   "id": "M051",
   "stage": "group",
   "group": "C",
   "dateET": "2026-06-24T18:00:00-04:00",
   "team1": "SCO",
   "team2": "BRA",
   "venueId": "MIA",
   "status": "scheduled",
   "score": null,
   "market": {
    "h": 0.1336,
    "x": 0.2078,
    "a": 0.6586,
    "book": "Bet365"
   }
  },
  {
   "id": "M052",
   "stage": "group",
   "group": "C",
   "dateET": "2026-06-24T18:00:00-04:00",
   "team1": "MAR",
   "team2": "HAI",
   "venueId": "ATL",
   "status": "scheduled",
   "score": null,
   "market": {
    "h": 0.7242,
    "x": 0.1712,
    "a": 0.1046,
    "book": "Bet365"
   }
  },
  {
   "id": "M053",
   "stage": "group",
   "group": "A",
   "dateET": "2026-06-24T21:00:00-04:00",
   "team1": "CZE",
   "team2": "MEX",
   "venueId": "MEX",
   "status": "scheduled",
   "score": null,
   "market": {
    "h": 0.2002,
    "x": 0.2716,
    "a": 0.5282,
    "book": "Bet365"
   }
  },
  {
   "id": "M054",
   "stage": "group",
   "group": "A",
   "dateET": "2026-06-24T21:00:00-04:00",
   "team1": "RSA",
   "team2": "KOR",
   "venueId": "MTY",
   "status": "scheduled",
   "score": null,
   "market": {
    "h": 0.1701,
    "x": 0.2339,
    "a": 0.596,
    "book": "Bet365"
   }
  },
  {
   "id": "M055",
   "stage": "group",
   "group": "E",
   "dateET": "2026-06-25T16:00:00-04:00",
   "team1": "ECU",
   "team2": "GER",
   "venueId": "NYNJ",
   "status": "scheduled",
   "score": null,
   "market": {
    "h": 0.1876,
    "x": 0.2606,
    "a": 0.5518,
    "book": "Bet365"
   }
  },
  {
   "id": "M056",
   "stage": "group",
   "group": "E",
   "dateET": "2026-06-25T16:00:00-04:00",
   "team1": "CUW",
   "team2": "CIV",
   "venueId": "PHI",
   "status": "scheduled",
   "score": null,
   "market": {
    "h": 0.0554,
    "x": 0.1108,
    "a": 0.8337,
    "book": "Bet365"
   }
  },
  {
   "id": "M057",
   "stage": "group",
   "group": "F",
   "dateET": "2026-06-25T19:00:00-04:00",
   "team1": "JPN",
   "team2": "SWE",
   "venueId": "DAL",
   "status": "scheduled",
   "score": null,
   "market": {
    "h": 0.4474,
    "x": 0.2763,
    "a": 0.2763,
    "book": "Bet365"
   }
  },
  {
   "id": "M058",
   "stage": "group",
   "group": "F",
   "dateET": "2026-06-25T19:00:00-04:00",
   "team1": "TUN",
   "team2": "NED",
   "venueId": "KC",
   "status": "scheduled",
   "score": null,
   "market": {
    "h": 0.0951,
    "x": 0.1901,
    "a": 0.7148,
    "book": "Bet365"
   }
  },
  {
   "id": "M059",
   "stage": "group",
   "group": "D",
   "dateET": "2026-06-25T22:00:00-04:00",
   "team1": "TUR",
   "team2": "USA",
   "venueId": "LA",
   "status": "scheduled",
   "score": null,
   "market": {
    "h": 0.3478,
    "x": 0.2609,
    "a": 0.3913,
    "book": "Bet365"
   }
  },
  {
   "id": "M060",
   "stage": "group",
   "group": "D",
   "dateET": "2026-06-25T22:00:00-04:00",
   "team1": "PAR",
   "team2": "AUS",
   "venueId": "SF",
   "status": "scheduled",
   "score": null,
   "market": {
    "h": 0.4374,
    "x": 0.2939,
    "a": 0.2687,
    "book": "Bet365"
   }
  },
  {
   "id": "M061",
   "stage": "group",
   "group": "I",
   "dateET": "2026-06-26T15:00:00-04:00",
   "team1": "NOR",
   "team2": "FRA",
   "venueId": "BOS",
   "status": "scheduled",
   "score": null,
   "market": {
    "h": 0.217,
    "x": 0.261,
    "a": 0.522,
    "book": "Bet365"
   }
  },
  {
   "id": "M062",
   "stage": "group",
   "group": "I",
   "dateET": "2026-06-26T15:00:00-04:00",
   "team1": "SEN",
   "team2": "IRQ",
   "venueId": "TOR",
   "status": "scheduled",
   "score": null,
   "market": {
    "h": 0.7159,
    "x": 0.1861,
    "a": 0.098,
    "book": "Bet365"
   }
  },
  {
   "id": "M063",
   "stage": "group",
   "group": "H",
   "dateET": "2026-06-26T20:00:00-04:00",
   "team1": "CPV",
   "team2": "KSA",
   "venueId": "HOU",
   "status": "scheduled",
   "score": null,
   "market": {
    "h": 0.3432,
    "x": 0.2551,
    "a": 0.4017,
    "book": "Bet365"
   }
  },
  {
   "id": "M064",
   "stage": "group",
   "group": "H",
   "dateET": "2026-06-26T20:00:00-04:00",
   "team1": "URU",
   "team2": "ESP",
   "venueId": "GDL",
   "status": "scheduled",
   "score": null,
   "market": {
    "h": 0.1643,
    "x": 0.2182,
    "a": 0.6175,
    "book": "Bet365"
   }
  },
  {
   "id": "M065",
   "stage": "group",
   "group": "G",
   "dateET": "2026-06-26T23:00:00-04:00",
   "team1": "EGY",
   "team2": "IRN",
   "venueId": "SEA",
   "status": "scheduled",
   "score": null,
   "market": {
    "h": 0.4573,
    "x": 0.3024,
    "a": 0.2404,
    "book": "Bet365"
   }
  },
  {
   "id": "M066",
   "stage": "group",
   "group": "G",
   "dateET": "2026-06-26T23:00:00-04:00",
   "team1": "NZL",
   "team2": "BEL",
   "venueId": "BCP",
   "status": "scheduled",
   "score": null,
   "market": {
    "h": 0.0849,
    "x": 0.1495,
    "a": 0.7656,
    "book": "Bet365"
   }
  },
  {
   "id": "M067",
   "stage": "group",
   "group": "L",
   "dateET": "2026-06-27T17:00:00-04:00",
   "team1": "PAN",
   "team2": "ENG",
   "venueId": "NYNJ",
   "status": "scheduled",
   "score": null,
   "market": {
    "h": 0.1043,
    "x": 0.1565,
    "a": 0.7392,
    "book": "Bet365"
   }
  },
  {
   "id": "M068",
   "stage": "group",
   "group": "L",
   "dateET": "2026-06-27T17:00:00-04:00",
   "team1": "CRO",
   "team2": "GHA",
   "venueId": "PHI",
   "status": "scheduled",
   "score": null,
   "market": {
    "h": 0.5811,
    "x": 0.2477,
    "a": 0.1712,
    "book": "Bet365"
   }
  },
  {
   "id": "M069",
   "stage": "group",
   "group": "K",
   "dateET": "2026-06-27T19:30:00-04:00",
   "team1": "COL",
   "team2": "POR",
   "venueId": "MIA",
   "status": "scheduled",
   "score": null,
   "market": {
    "h": 0.2744,
    "x": 0.2916,
    "a": 0.434,
    "book": "Bet365"
   }
  },
  {
   "id": "M070",
   "stage": "group",
   "group": "K",
   "dateET": "2026-06-27T19:30:00-04:00",
   "team1": "COD",
   "team2": "UZB",
   "venueId": "ATL",
   "status": "scheduled",
   "score": null,
   "market": {
    "h": 0.4416,
    "x": 0.2792,
    "a": 0.2792,
    "book": "Bet365"
   }
  },
  {
   "id": "M071",
   "stage": "group",
   "group": "J",
   "dateET": "2026-06-27T22:00:00-04:00",
   "team1": "ALG",
   "team2": "AUT",
   "venueId": "KC",
   "status": "scheduled",
   "score": null,
   "market": {
    "h": 0.3231,
    "x": 0.3022,
    "a": 0.3747,
    "book": "Bet365"
   }
  },
  {
   "id": "M072",
   "stage": "group",
   "group": "J",
   "dateET": "2026-06-27T22:00:00-04:00",
   "team1": "JOR",
   "team2": "ARG",
   "venueId": "DAL",
   "status": "scheduled",
   "score": null,
   "market": {
    "h": 0.0852,
    "x": 0.1339,
    "a": 0.7809,
    "book": "Bet365"
   }
  }
 ],
 "r32Template": [
  {
   "id": "R32-3",
   "date": "Mon Jun 29",
   "venueId": "BOS",
   "a": {
    "type": "group",
    "group": "E",
    "place": 1
   },
   "b": {
    "type": "third",
    "groups": [
     "A",
     "B",
     "C",
     "D",
     "F"
    ]
   },
   "label": "E1 vs 3rd A/B/C/D/F",
   "matchNo": 74
  },
  {
   "id": "R32-6",
   "date": "Tue Jun 30",
   "venueId": "NYNJ",
   "a": {
    "type": "group",
    "group": "I",
    "place": 1
   },
   "b": {
    "type": "third",
    "groups": [
     "C",
     "D",
     "F",
     "G",
     "H"
    ]
   },
   "label": "I1 vs 3rd C/D/F/G/H",
   "matchNo": 77
  },
  {
   "id": "R32-1",
   "date": "Sun Jun 28",
   "venueId": "LA",
   "a": {
    "type": "group",
    "group": "A",
    "place": 2
   },
   "b": {
    "type": "group",
    "group": "B",
    "place": 2
   },
   "label": "A2 vs B2",
   "matchNo": 73
  },
  {
   "id": "R32-4",
   "date": "Mon Jun 29",
   "venueId": "MTY",
   "a": {
    "type": "group",
    "group": "F",
    "place": 1
   },
   "b": {
    "type": "group",
    "group": "C",
    "place": 2
   },
   "label": "F1 vs C2",
   "matchNo": 75
  },
  {
   "id": "R32-12",
   "date": "Thu Jul 2",
   "venueId": "TOR",
   "a": {
    "type": "group",
    "group": "K",
    "place": 2
   },
   "b": {
    "type": "group",
    "group": "L",
    "place": 2
   },
   "label": "K2 vs L2",
   "matchNo": 83
  },
  {
   "id": "R32-11",
   "date": "Thu Jul 2",
   "venueId": "LA",
   "a": {
    "type": "group",
    "group": "H",
    "place": 1
   },
   "b": {
    "type": "group",
    "group": "J",
    "place": 2
   },
   "label": "H1 vs J2",
   "matchNo": 84
  },
  {
   "id": "R32-10",
   "date": "Wed Jul 1",
   "venueId": "SF",
   "a": {
    "type": "group",
    "group": "D",
    "place": 1
   },
   "b": {
    "type": "third",
    "groups": [
     "B",
     "E",
     "F",
     "I",
     "J"
    ]
   },
   "label": "D1 vs 3rd B/E/F/I/J",
   "matchNo": 81
  },
  {
   "id": "R32-9",
   "date": "Wed Jul 1",
   "venueId": "SEA",
   "a": {
    "type": "group",
    "group": "G",
    "place": 1
   },
   "b": {
    "type": "third",
    "groups": [
     "A",
     "E",
     "H",
     "I",
     "J"
    ]
   },
   "label": "G1 vs 3rd A/E/H/I/J",
   "matchNo": 82
  },
  {
   "id": "R32-2",
   "date": "Mon Jun 29",
   "venueId": "HOU",
   "a": {
    "type": "group",
    "group": "C",
    "place": 1
   },
   "b": {
    "type": "group",
    "group": "F",
    "place": 2
   },
   "label": "C1 vs F2",
   "matchNo": 76
  },
  {
   "id": "R32-5",
   "date": "Tue Jun 30",
   "venueId": "DAL",
   "a": {
    "type": "group",
    "group": "E",
    "place": 2
   },
   "b": {
    "type": "group",
    "group": "I",
    "place": 2
   },
   "label": "E2 vs I2",
   "matchNo": 78
  },
  {
   "id": "R32-7",
   "date": "Tue Jun 30",
   "venueId": "MEX",
   "a": {
    "type": "group",
    "group": "A",
    "place": 1
   },
   "b": {
    "type": "third",
    "groups": [
     "C",
     "E",
     "F",
     "H",
     "I"
    ]
   },
   "label": "A1 vs 3rd C/E/F/H/I",
   "matchNo": 79
  },
  {
   "id": "R32-8",
   "date": "Wed Jul 1",
   "venueId": "ATL",
   "a": {
    "type": "group",
    "group": "L",
    "place": 1
   },
   "b": {
    "type": "third",
    "groups": [
     "E",
     "H",
     "I",
     "J",
     "K"
    ]
   },
   "label": "L1 vs 3rd E/H/I/J/K",
   "matchNo": 80
  },
  {
   "id": "R32-15",
   "date": "Fri Jul 3",
   "venueId": "MIA",
   "a": {
    "type": "group",
    "group": "J",
    "place": 1
   },
   "b": {
    "type": "group",
    "group": "H",
    "place": 2
   },
   "label": "J1 vs H2",
   "matchNo": 86
  },
  {
   "id": "R32-14",
   "date": "Fri Jul 3",
   "venueId": "DAL",
   "a": {
    "type": "group",
    "group": "D",
    "place": 2
   },
   "b": {
    "type": "group",
    "group": "G",
    "place": 2
   },
   "label": "D2 vs G2",
   "matchNo": 88
  },
  {
   "id": "R32-13",
   "date": "Thu Jul 2",
   "venueId": "BCP",
   "a": {
    "type": "group",
    "group": "B",
    "place": 1
   },
   "b": {
    "type": "third",
    "groups": [
     "E",
     "F",
     "G",
     "I",
     "J"
    ]
   },
   "label": "B1 vs 3rd E/F/G/I/J",
   "matchNo": 85
  },
  {
   "id": "R32-16",
   "date": "Fri Jul 3",
   "venueId": "KC",
   "a": {
    "type": "group",
    "group": "K",
    "place": 1
   },
   "b": {
    "type": "third",
    "groups": [
     "D",
     "E",
     "I",
     "J",
     "L"
    ]
   },
   "label": "K1 vs 3rd D/E/I/J/L",
   "matchNo": 87
  }
 ],
 "koSchedule": [
  {
   "round": "Round of 32",
   "date": "Sun Jun 28",
   "venueId": "LA",
   "match": "A runners-up vs B runners-up",
   "timeET": "3:00pm ET"
  },
  {
   "round": "Round of 32",
   "date": "Mon Jun 29",
   "venueId": "HOU",
   "match": "C winners vs F runners-up",
   "timeET": "1:00pm ET"
  },
  {
   "round": "Round of 32",
   "date": "Mon Jun 29",
   "venueId": "BOS",
   "match": "E winners vs third-place qualifier",
   "timeET": "4:30pm ET"
  },
  {
   "round": "Round of 32",
   "date": "Mon Jun 29",
   "venueId": "MTY",
   "match": "F winners vs C runners-up",
   "timeET": "9:00pm ET"
  },
  {
   "round": "Round of 32",
   "date": "Tue Jun 30",
   "venueId": "DAL",
   "match": "E runners-up vs I runners-up",
   "timeET": "1:00pm ET"
  },
  {
   "round": "Round of 32",
   "date": "Tue Jun 30",
   "venueId": "NYNJ",
   "match": "I winners vs third-place qualifier",
   "timeET": "5:00pm ET"
  },
  {
   "round": "Round of 32",
   "date": "Tue Jun 30",
   "venueId": "MEX",
   "match": "A winners vs third-place qualifier",
   "timeET": "9:00pm ET"
  },
  {
   "round": "Round of 32",
   "date": "Wed Jul 1",
   "venueId": "ATL",
   "match": "L winners vs third-place qualifier",
   "timeET": "12:00pm ET"
  },
  {
   "round": "Round of 32",
   "date": "Wed Jul 1",
   "venueId": "SEA",
   "match": "G winners vs third-place qualifier",
   "timeET": "4:00pm ET"
  },
  {
   "round": "Round of 32",
   "date": "Wed Jul 1",
   "venueId": "SF",
   "match": "D winners vs third-place qualifier",
   "timeET": "8:00pm ET"
  },
  {
   "round": "Round of 32",
   "date": "Thu Jul 2",
   "venueId": "LA",
   "match": "H winners vs J runners-up",
   "timeET": "3:00pm ET"
  },
  {
   "round": "Round of 32",
   "date": "Thu Jul 2",
   "venueId": "TOR",
   "match": "K runners-up vs L runners-up",
   "timeET": "7:00pm ET"
  },
  {
   "round": "Round of 32",
   "date": "Thu Jul 2",
   "venueId": "BCP",
   "match": "B winners vs third-place qualifier",
   "timeET": "11:00pm ET"
  },
  {
   "round": "Round of 32",
   "date": "Fri Jul 3",
   "venueId": "DAL",
   "match": "D runners-up vs G runners-up",
   "timeET": "2:00pm ET"
  },
  {
   "round": "Round of 32",
   "date": "Fri Jul 3",
   "venueId": "MIA",
   "match": "J winners vs H runners-up",
   "timeET": "6:00pm ET"
  },
  {
   "round": "Round of 32",
   "date": "Fri Jul 3",
   "venueId": "KC",
   "match": "K winners vs third-place qualifier",
   "timeET": "9:30pm ET"
  },
  {
   "round": "Round of 16",
   "date": "Jul 4-7",
   "venueId": "HOU",
   "match": "Eight Round-of-16 matches across Houston, Philadelphia, NYNJ, Mexico City, Dallas, Seattle, Atlanta and Vancouver",
   "timeET": "various"
  },
  {
   "round": "Quarter-finals",
   "date": "Jul 9-11",
   "venueId": "BOS",
   "match": "Four quarter-finals across Boston, Los Angeles, Miami and Kansas City",
   "timeET": "various"
  },
  {
   "round": "Semi-finals",
   "date": "Jul 14-15",
   "venueId": "DAL",
   "match": "Semi-final 1 in Dallas; Semi-final 2 in Atlanta",
   "timeET": "3:00pm ET / 3:00pm ET"
  },
  {
   "round": "Third-place game",
   "date": "Sat Jul 18",
   "venueId": "MIA",
   "match": "Third-place game",
   "timeET": "5:00pm ET"
  },
  {
   "round": "Final",
   "date": "Sun Jul 19",
   "venueId": "NYNJ",
   "match": "World Cup Final",
   "timeET": "3:00pm ET"
  }
 ],
 "mena": [
  "QAT",
  "MAR",
  "TUN",
  "EGY",
  "IRN",
  "KSA",
  "IRQ",
  "ALG",
  "JOR"
 ],
 "watchlist": [
  {
   "player": "Kylian Mbappé",
   "team": "FRA",
   "note": "Real Madrid"
  },
  {
   "player": "Lionel Messi",
   "team": "ARG",
   "note": "Inter Miami"
  },
  {
   "player": "Jude Bellingham",
   "team": "ENG",
   "note": "Real Madrid"
  },
  {
   "player": "Mohamed Salah",
   "team": "EGY",
   "note": "Liverpool"
  }
 ],
 "league": {
  "entries": [
   {
    "n": "Abdullah Khaled",
    "w": {
     "A": "MEX",
     "B": "CAN",
     "C": "BRA",
     "D": "USA",
     "E": "GER",
     "F": "NED",
     "G": "BEL",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "BRA",
     "FRA"
    ],
    "c": "BRA",
    "locked": "2026-06-12"
   },
   {
    "n": "Fahad Khaled",
    "w": {
     "A": "KOR",
     "B": "SUI",
     "C": "MAR",
     "D": "TUR",
     "E": "GER",
     "F": "NED",
     "G": "EGY",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "POR",
     "NED"
    ],
    "c": "POR",
    "locked": "2026-06-12"
   },
   {
    "n": "Khaled Fahad",
    "w": {
     "A": "MEX",
     "B": "CAN",
     "C": "BRA",
     "D": "USA",
     "E": "GER",
     "F": "NED",
     "G": "BEL",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "CRO"
    },
    "f": [
     "POR",
     "ESP"
    ],
    "c": "ESP",
    "locked": "2026-06-12"
   },
   {
    "n": "Essa",
    "w": {
     "A": "KOR",
     "B": "SUI",
     "C": "BRA",
     "D": "AUS",
     "E": "GER",
     "F": "NED",
     "G": "BEL",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "NED",
     "POR"
    ],
    "c": "NED",
    "locked": "2026-06-12"
   },
   {
    "n": "Wahab Bader",
    "w": {
     "A": "MEX",
     "B": "SUI",
     "C": "BRA",
     "D": "TUR",
     "E": "GER",
     "F": "NED",
     "G": "BEL",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "ARG",
     "ESP"
    ],
    "c": "ARG",
    "locked": "2026-06-12"
   },
   {
    "n": "Nasser Talal",
    "w": {
     "A": "MEX",
     "B": "SUI",
     "C": "BRA",
     "D": "USA",
     "E": "GER",
     "F": "NED",
     "G": "BEL",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "ENG",
     "ESP"
    ],
    "c": "ENG",
    "locked": "2026-06-12"
   },
   {
    "n": "Hmoud Al Sabah",
    "w": {
     "A": "MEX",
     "B": "CAN",
     "C": "BRA",
     "D": "TUR",
     "E": "ECU",
     "F": "NED",
     "G": "BEL",
     "H": "ESP",
     "I": "NOR",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "ESP",
     "POR"
    ],
    "c": "ESP",
    "locked": "2026-06-12"
   },
   {
    "n": "Alibaba",
    "w": {
     "A": "MEX",
     "B": "BIH",
     "C": "MAR",
     "D": "TUR",
     "E": "GER",
     "F": "NED",
     "G": "BEL",
     "H": "KSA",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "KSA",
     "IRN"
    ],
    "c": "IRN",
    "locked": "2026-06-12"
   },
   {
    "n": "Nasser Fahad",
    "w": {
     "A": "MEX",
     "B": "SUI",
     "C": "BRA",
     "D": "TUR",
     "E": "GER",
     "F": "NED",
     "G": "IRN",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "ESP",
     "POR"
    ],
    "c": "ESP",
    "locked": "2026-06-12"
   },
   {
    "n": "Mohammed Jamal",
    "w": {
     "A": "KOR",
     "B": "BIH",
     "C": "BRA",
     "D": "TUR",
     "E": "GER",
     "F": "NED",
     "G": "BEL",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "FRA",
     "ARG"
    ],
    "c": "FRA",
    "locked": "2026-06-12"
   },
   {
    "n": "Salem Athbi",
    "w": {
     "A": "MEX",
     "B": "SUI",
     "C": "BRA",
     "D": "TUR",
     "E": "GER",
     "F": "NED",
     "G": "BEL",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "GER",
     "BRA"
    ],
    "c": "GER",
    "locked": "2026-06-12"
   },
   {
    "n": "Thamer Fares Alnoon",
    "w": {
     "A": "MEX",
     "B": "BIH",
     "C": "BRA",
     "D": "USA",
     "E": "GER",
     "F": "SWE",
     "G": "BEL",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "ESP",
     "BRA"
    ],
    "c": "BRA",
    "locked": "2026-06-12"
   },
   {
    "n": "Ahmed Boareki",
    "w": {
     "A": "MEX",
     "B": "SUI",
     "C": "BRA",
     "D": "PAR",
     "E": "GER",
     "F": "NED",
     "G": "BEL",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "CRO"
    },
    "f": [
     "ARG",
     "FRA"
    ],
    "c": "FRA",
    "locked": "2026-06-12"
   },
   {
    "n": "Mama Aad",
    "w": {
     "A": "MEX",
     "B": "SUI",
     "C": "BRA",
     "D": "TUR",
     "E": "GER",
     "F": "SWE",
     "G": "BEL",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "ESP",
     "POR"
    ],
    "c": "POR",
    "locked": "2026-06-12"
   },
   {
    "n": "Fahad Ali",
    "w": {
     "A": "MEX",
     "B": "SUI",
     "C": "BRA",
     "D": "USA",
     "E": "GER",
     "F": "NED",
     "G": "EGY",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "CRO"
    },
    "f": [
     "NED",
     "POR"
    ],
    "c": "NED",
    "locked": "2026-06-12"
   },
   {
    "n": "Ali Ahmed Hmoud Mohammed",
    "w": {
     "A": "MEX",
     "B": "SUI",
     "C": "BRA",
     "D": "USA",
     "E": "GER",
     "F": "SWE",
     "G": "BEL",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "ESP",
     "ENG"
    ],
    "c": "ESP",
    "locked": "2026-06-12"
   },
   {
    "n": "Eric Bartlett",
    "w": {
     "A": "MEX",
     "B": "BIH",
     "C": "BRA",
     "D": "TUR",
     "E": "GER",
     "F": "NED",
     "G": "BEL",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "CRO"
    },
    "f": [
     "FRA",
     "ENG"
    ],
    "c": "FRA",
    "locked": "2026-06-12"
   },
   {
    "n": "JMAMS",
    "w": {
     "A": "MEX",
     "B": "SUI",
     "C": "BRA",
     "D": "USA",
     "E": "ECU",
     "F": "NED",
     "G": "BEL",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "ENG",
     "FRA"
    ],
    "c": "ENG",
    "locked": "2026-06-12"
   },
   {
    "n": "Saleh Boareki",
    "w": {
     "A": "KOR",
     "B": "SUI",
     "C": "MAR",
     "D": "TUR",
     "E": "ECU",
     "F": "NED",
     "G": "EGY",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "FRA",
     "ENG"
    ],
    "c": "ENG",
    "locked": "2026-06-12"
   },
   {
    "n": "Faisal Boodai",
    "w": {
     "A": "MEX",
     "B": "SUI",
     "C": "BRA",
     "D": "AUS",
     "E": "GER",
     "F": "NED",
     "G": "BEL",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "CRO"
    },
    "f": [
     "POR",
     "ESP"
    ],
    "c": "POR",
    "locked": "2026-06-12"
   },
   {
    "n": "AMAS",
    "w": {
     "A": "MEX",
     "B": "QAT",
     "C": "MAR",
     "D": "TUR",
     "E": "CIV",
     "F": "TUN",
     "G": "EGY",
     "H": "KSA",
     "I": "SEN",
     "J": "ARG",
     "K": "UZB",
     "L": "GHA"
    },
    "f": [
     "SEN",
     "ARG"
    ],
    "c": "SEN",
    "locked": "2026-06-12"
   },
   {
    "n": "Abdullah Mohammed",
    "w": {
     "A": "MEX",
     "B": "QAT",
     "C": "BRA",
     "D": "TUR",
     "E": "GER",
     "F": "NED",
     "G": "EGY",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "GER",
     "ENG"
    ],
    "c": "ENG",
    "locked": "2026-06-12"
   },
   {
    "n": "Feras Al Qenaei",
    "w": {
     "A": "MEX",
     "B": "SUI",
     "C": "BRA",
     "D": "TUR",
     "E": "GER",
     "F": "NED",
     "G": "BEL",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "ESP",
     "POR"
    ],
    "c": "ESP",
    "locked": "2026-06-12"
   },
   {
    "n": "Moblee",
    "w": {
     "A": "MEX",
     "B": "CAN",
     "C": "BRA",
     "D": "USA",
     "E": "GER",
     "F": "JPN",
     "G": "BEL",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "ESP",
     "BRA"
    ],
    "c": "ESP",
    "locked": "2026-06-12"
   },
   {
    "n": "Shamlan Abdulaziz",
    "w": {
     "A": "MEX",
     "B": "SUI",
     "C": "BRA",
     "D": "TUR",
     "E": "GER",
     "F": "NED",
     "G": "BEL",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "BRA",
     "FRA"
    ],
    "c": "BRA",
    "locked": "2026-06-12"
   },
   {
    "n": "Mohammad Ahmad",
    "w": {
     "A": "MEX",
     "B": "CAN",
     "C": "BRA",
     "D": "USA",
     "E": "GER",
     "F": "JPN",
     "G": "BEL",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "CRO"
    },
    "f": [
     "FRA",
     "ARG"
    ],
    "c": "FRA",
    "locked": "2026-06-12"
   },
   {
    "n": "Bader Al Gatheebi",
    "w": {
     "A": "MEX",
     "B": "SUI",
     "C": "BRA",
     "D": "USA",
     "E": "GER",
     "F": "NED",
     "G": "BEL",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "ESP",
     "ENG"
    ],
    "c": "ESP",
    "locked": "2026-06-12"
   },
   {
    "n": "Faisal Jaber Al Sabah",
    "w": {
     "A": "MEX",
     "B": "SUI",
     "C": "BRA",
     "D": "USA",
     "E": "GER",
     "F": "NED",
     "G": "BEL",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "POR",
     "FRA"
    ],
    "c": "POR",
    "locked": "2026-06-12"
   },
   {
    "n": "Bader Mohamad Alnomas",
    "w": {
     "A": "MEX",
     "B": "SUI",
     "C": "BRA",
     "D": "USA",
     "E": "GER",
     "F": "NED",
     "G": "BEL",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "NED",
     "POR"
    ],
    "c": "NED",
    "locked": "2026-06-12"
   },
   {
    "n": "Arsenal #1",
    "w": {
     "A": "MEX",
     "B": "SUI",
     "C": "MAR",
     "D": "TUR",
     "E": "GER",
     "F": "NED",
     "G": "BEL",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "POR",
     "FRA"
    ],
    "c": "POR",
    "locked": "2026-06-12"
   },
   {
    "n": "Jogs Bonito",
    "w": {
     "A": "MEX",
     "B": "SUI",
     "C": "BRA",
     "D": "TUR",
     "E": "GER",
     "F": "JPN",
     "G": "EGY",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "ESP",
     "POR"
    ],
    "c": "POR",
    "locked": "2026-06-12"
   },
   {
    "n": "Naser AlQadiri",
    "w": {
     "A": "MEX",
     "B": "BIH",
     "C": "BRA",
     "D": "USA",
     "E": "GER",
     "F": "NED",
     "G": "BEL",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "CRO"
    },
    "f": [
     "POR",
     "ESP"
    ],
    "c": "POR",
    "locked": "2026-06-12"
   },
   {
    "n": "Ahmed Mubarak Al Sabah",
    "w": {
     "A": "MEX",
     "B": "CAN",
     "C": "BRA",
     "D": "TUR",
     "E": "GER",
     "F": "SWE",
     "G": "BEL",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "CRO"
    },
    "f": [
     "POR",
     "ESP"
    ],
    "c": "POR",
    "locked": "2026-06-12"
   },
   {
    "n": "MoSabs",
    "w": {
     "A": "MEX",
     "B": "CAN",
     "C": "BRA",
     "D": "TUR",
     "E": "GER",
     "F": "NED",
     "G": "BEL",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "ENG",
     "NED"
    ],
    "c": "NED",
    "locked": "2026-06-12",
    "exhibition": true
   },
   {
    "n": "Rashed",
    "w": {
     "A": "MEX",
     "B": "SUI",
     "C": "BRA",
     "D": "USA",
     "E": "GER",
     "F": "NED",
     "G": "EGY",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "BRA",
     "ESP"
    ],
    "c": "ESP",
    "locked": "2026-06-12"
   },
   {
    "n": "HMB",
    "w": {
     "A": "MEX",
     "B": "CAN",
     "C": "BRA",
     "D": "USA",
     "E": "GER",
     "F": "NED",
     "G": "BEL",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "ARG",
     "ESP"
    ],
    "c": "ESP",
    "locked": "2026-06-12"
   },
   {
    "n": "Faisal Abu Hadida",
    "w": {
     "A": "MEX",
     "B": "SUI",
     "C": "BRA",
     "D": "USA",
     "E": "GER",
     "F": "NED",
     "G": "BEL",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "ENG",
     "NED"
    ],
    "c": "ENG",
    "locked": "2026-06-12"
   },
   {
    "n": "Jarah Aladwani",
    "w": {
     "A": "MEX",
     "B": "CAN",
     "C": "BRA",
     "D": "PAR",
     "E": "GER",
     "F": "NED",
     "G": "BEL",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "BRA",
     "FRA"
    ],
    "c": "FRA",
    "locked": "2026-06-12"
   },
   {
    "n": "Sabah Mohammed",
    "w": {
     "A": "MEX",
     "B": "SUI",
     "C": "BRA",
     "D": "TUR",
     "E": "GER",
     "F": "NED",
     "G": "BEL",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "POR",
     "FRA"
    ],
    "c": "POR",
    "locked": "2026-06-12"
   },
   {
    "n": "Syb",
    "w": {
     "A": "MEX",
     "B": "SUI",
     "C": "BRA",
     "D": "TUR",
     "E": "GER",
     "F": "NED",
     "G": "BEL",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "CRO"
    },
    "f": [
     "FRA",
     "POR"
    ],
    "c": "FRA",
    "locked": "2026-06-13"
   },
   {
    "n": "Gelenn Caley Cale",
    "w": {
     "A": "MEX",
     "B": "SUI",
     "C": "BRA",
     "D": "TUR",
     "E": "GER",
     "F": "NED",
     "G": "BEL",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "BRA",
     "ESP"
    ],
    "c": "BRA",
    "locked": "2026-06-13"
   },
   {
    "n": "Saleh Al Hashash",
    "w": {
     "A": "MEX",
     "B": "SUI",
     "C": "BRA",
     "D": "USA",
     "E": "GER",
     "F": "NED",
     "G": "BEL",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "ESP",
     "POR"
    ],
    "c": "ESP",
    "locked": "2026-06-13"
   },
   {
    "n": "Khaled Al Qahtani",
    "w": {
     "A": "MEX",
     "B": "SUI",
     "C": "BRA",
     "D": "USA",
     "E": "GER",
     "F": "SWE",
     "G": "BEL",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "POR",
     "ESP"
    ],
    "c": "ESP",
    "locked": "2026-06-13"
   },
   {
    "n": "Khalifa ali",
    "w": {
     "A": "KOR",
     "B": "SUI",
     "C": "BRA",
     "D": "USA",
     "E": "GER",
     "F": "NED",
     "G": "BEL",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "POR",
     "NED"
    ],
    "c": "NED",
    "locked": "2026-06-13"
   },
   {
    "n": "Khaled ali",
    "w": {
     "A": "KOR",
     "B": "SUI",
     "C": "BRA",
     "D": "TUR",
     "E": "ECU",
     "F": "NED",
     "G": "BEL",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "ECU",
     "ARG"
    ],
    "c": "ECU",
    "locked": "2026-06-13"
   },
   {
    "n": "Khalifa zayed",
    "w": {
     "A": "MEX",
     "B": "SUI",
     "C": "BRA",
     "D": "TUR",
     "E": "GER",
     "F": "NED",
     "G": "BEL",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "BRA",
     "ESP"
    ],
    "c": "BRA",
    "locked": "2026-06-13"
   },
   {
    "n": "Abdulaziz Alsabah",
    "w": {
     "A": "KOR",
     "B": "SUI",
     "C": "BRA",
     "D": "USA",
     "E": "GER",
     "F": "NED",
     "G": "BEL",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "POR",
     "ESP"
    ],
    "c": "POR",
    "locked": "2026-06-13"
   },
   {
    "n": "Chris Ovenden",
    "w": {
     "A": "MEX",
     "B": "SUI",
     "C": "BRA",
     "D": "USA",
     "E": "GER",
     "F": "JPN",
     "G": "BEL",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "ESP",
     "ENG"
    ],
    "c": "ESP",
    "locked": "2026-06-14"
   },
   {
    "n": "Zuz",
    "w": {
     "A": "KOR",
     "B": "QAT",
     "C": "BRA",
     "D": "TUR",
     "E": "GER",
     "F": "NED",
     "G": "EGY",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "BRA",
     "FRA"
    ],
    "c": "BRA",
    "locked": "2026-06-14"
   },
   {
    "n": "AD",
    "w": {
     "A": "MEX",
     "B": "SUI",
     "C": "BRA",
     "D": "USA",
     "E": "GER",
     "F": "JPN",
     "G": "BEL",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "FRA",
     "POR"
    ],
    "c": "FRA",
    "locked": "2026-06-15"
   },
   {
    "n": "Mohammed Behbehani",
    "w": {
     "A": "MEX",
     "B": "SUI",
     "C": "BRA",
     "D": "AUS",
     "E": "GER",
     "F": "SWE",
     "G": "BEL",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "FRA",
     "ENG"
    ],
    "c": "ENG",
    "locked": "2026-06-15"
   },
   {
    "n": "Hani Ibraheam sulaiman abdullah al mawash",
    "w": {
     "A": "MEX",
     "B": "SUI",
     "C": "MAR",
     "D": "USA",
     "E": "GER",
     "F": "NED",
     "G": "EGY",
     "H": "ESP",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "GER",
     "ARG"
    ],
    "c": "GER",
    "locked": "2026-06-16"
   },
   {
    "n": "Abdullah Mubarak",
    "w": {
     "A": "KOR",
     "B": "QAT",
     "C": "MAR",
     "D": "TUR",
     "E": "GER",
     "F": "NED",
     "G": "EGY",
     "H": "KSA",
     "I": "FRA",
     "J": "ARG",
     "K": "POR",
     "L": "ENG"
    },
    "f": [
     "MAR",
     "FRA"
    ],
    "c": "MAR",
    "locked": "2026-06-17"
   }
  ],
  "scoring": {
   "groupWinner": 2,
   "finalist": 4,
   "champion": 10
  },
  "props": [
   {
    "gb": {
     "p": "Messi",
     "t": "ARG"
    },
    "as": {
     "p": "Bruno",
     "t": "POR"
    },
    "cards": "ARG",
    "goals": "ENG",
    "mena": "QAT",
    "host": "MEX",
    "tg": 133,
    "n": "Abdullah Mohammed",
    "locked": "2026-06-12"
   },
   {
    "gb": {
     "p": "Igor Thiago",
     "t": "BRA"
    },
    "as": {
     "p": "Lamine yamal",
     "t": "ESP"
    },
    "cards": "ECU",
    "goals": "ESP",
    "mena": "MAR",
    "host": "MEX",
    "tg": 259,
    "n": "Hmoud Al Sabah",
    "locked": "2026-06-12"
   },
   {
    "gb": {
     "p": "Dembele",
     "t": "FRA"
    },
    "as": {
     "p": "Bruno Fernandes",
     "t": "POR"
    },
    "cards": "ESP",
    "goals": "FRA",
    "mena": "MAR",
    "host": "MEX",
    "tg": 274,
    "n": "Ali Ahmed Hmoud Mohammed",
    "locked": "2026-06-12"
   },
   {
    "gb": {
     "p": "Mbappe",
     "t": "FRA"
    },
    "as": {
     "p": "Lamine yamal",
     "t": "ESP"
    },
    "cards": "BRA",
    "goals": "ESP",
    "mena": "MAR",
    "host": "MEX",
    "tg": 263,
    "n": "Feras Al Qenaei",
    "locked": "2026-06-12"
   },
   {
    "gb": {
     "p": "Mbappe",
     "t": "FRA"
    },
    "as": {
     "p": "Bruno Fernandes",
     "t": "POR"
    },
    "cards": "RSA",
    "goals": "FRA",
    "mena": "MAR",
    "host": "USA",
    "tg": 257,
    "n": "Mohammed Jamal",
    "locked": "2026-06-12"
   },
   {
    "gb": {
     "p": "Hallaand",
     "t": "NOR"
    },
    "as": {
     "p": "Ounahi",
     "t": "MAR"
    },
    "cards": "MEX",
    "goals": "POR",
    "mena": "MAR",
    "host": "MEX",
    "tg": 194,
    "n": "Fahad Khaled",
    "locked": "2026-06-12"
   },
   {
    "gb": {
     "p": "Mbappe",
     "t": "FRA"
    },
    "as": {
     "p": "Lamine yamal",
     "t": "ESP"
    },
    "cards": "BRA",
    "goals": "FRA",
    "mena": "MAR",
    "host": "MEX",
    "tg": 265,
    "n": "Mama Aad",
    "locked": "2026-06-12"
   },
   {
    "gb": {
     "p": "Rashford",
     "t": "ENG"
    },
    "as": {
     "p": "Messi",
     "t": "ARG"
    },
    "cards": "RSA",
    "goals": "ESP",
    "mena": "MAR",
    "host": "MEX",
    "tg": 178,
    "n": "Khaled Fahad",
    "locked": "2026-06-12"
   },
   {
    "gb": {
     "p": "Vinicius",
     "t": "BRA"
    },
    "as": {
     "p": "Vinicius",
     "t": "BRA"
    },
    "cards": "IRQ",
    "goals": "FRA",
    "mena": "EGY",
    "host": "MEX",
    "tg": 179,
    "n": "Essa",
    "locked": "2026-06-12"
   },
   {
    "gb": {
     "p": "Mbappe",
     "t": "FRA"
    },
    "as": {
     "p": "Olise",
     "t": "FRA"
    },
    "cards": "URU",
    "goals": "FRA",
    "mena": "MAR",
    "host": "USA",
    "tg": 234,
    "n": "Nasser Fahad",
    "locked": "2026-06-12"
   },
   {
    "gb": {
     "p": "Ronado",
     "t": "POR"
    },
    "as": {
     "p": "Havars",
     "t": "GER"
    },
    "cards": "ALG",
    "goals": "BRA",
    "mena": "MAR",
    "host": "MEX",
    "tg": 166,
    "n": "Ahmed Boareki",
    "locked": "2026-06-12"
   },
   {
    "gb": {
     "p": "Mbappe",
     "t": "FRA"
    },
    "as": {
     "p": "Bruno Fernandes",
     "t": "POR"
    },
    "cards": "NED",
    "goals": "FRA",
    "mena": "MAR",
    "host": "MEX",
    "tg": 208,
    "n": "Ahmed Mubarak Al Sabah",
    "locked": "2026-06-12"
   },
   {
    "gb": {
     "p": "Dembele",
     "t": "FRA"
    },
    "as": {
     "p": "Vitinha",
     "t": "POR"
    },
    "cards": "SEN",
    "goals": "ESP",
    "mena": "MAR",
    "host": "CAN",
    "tg": 86,
    "n": "Saleh Boareki",
    "locked": "2026-06-12"
   },
   {
    "gb": {
     "p": "Mbappe",
     "t": "FRA"
    },
    "as": {
     "p": "Bruno",
     "t": "POR"
    },
    "cards": "ENG",
    "goals": "POR",
    "mena": "MAR",
    "host": "MEX",
    "tg": 250,
    "n": "Sabah Mohammed",
    "locked": "2026-06-12"
   },
   {
    "gb": {
     "p": "Harry Kane",
     "t": "ENG"
    },
    "as": {
     "p": "Bruno Fernandes",
     "t": "POR"
    },
    "cards": "POR",
    "goals": "ENG",
    "mena": "IRN",
    "host": "USA",
    "tg": 313,
    "n": "Nasser Talal",
    "locked": "2026-06-12"
   },
   {
    "gb": {
     "p": "Mbappe",
     "t": "FRA"
    },
    "as": {
     "p": "Lamine Yamal",
     "t": "ESP"
    },
    "cards": "ESP",
    "goals": "BRA",
    "mena": "MAR",
    "host": "USA",
    "tg": 245,
    "n": "Saleh Al Hashash",
    "locked": "2026-06-13"
   },
   {
    "gb": {
     "p": "Mbappe",
     "t": "FRA"
    },
    "as": {
     "p": "Bruno Fernandes",
     "t": "POR"
    },
    "cards": "BIH",
    "goals": "FRA",
    "mena": "MAR",
    "host": "USA",
    "tg": 264,
    "n": "Eric Bartlett",
    "locked": "2026-06-13"
   },
   {
    "gb": {
     "p": "Mbappé",
     "t": "FRA"
    },
    "as": {
     "p": "Bruno Fernandes",
     "t": "POR"
    },
    "cards": "ECU",
    "goals": "FRA",
    "mena": "MAR",
    "host": "MEX",
    "tg": 180,
    "n": "Khalifa zayed",
    "locked": "2026-06-13"
   },
   {
    "gb": {
     "p": "Harry Kane",
     "t": "ENG"
    },
    "as": {
     "p": "Alexis Mac Allister",
     "t": "ARG"
    },
    "cards": "ECU",
    "goals": "ESP",
    "mena": "MAR",
    "host": "USA",
    "tg": 221,
    "n": "Fahad jaber",
    "locked": "2026-06-13"
   },
   {
    "gb": {
     "p": "Ousmane Dembélé",
     "t": "FRA"
    },
    "as": {
     "p": "Cherki",
     "t": "FRA"
    },
    "cards": "RSA",
    "goals": "FRA",
    "mena": "ALG",
    "host": "USA",
    "tg": 193,
    "n": "Mohammad Ahmad Nasser",
    "locked": "2026-06-13"
   },
   {
    "gb": {
     "p": "Mbappe",
     "t": "FRA"
    },
    "as": {
     "p": "Messi",
     "t": "ARG"
    },
    "cards": "ARG",
    "goals": "FRA",
    "mena": "ALG",
    "host": "MEX",
    "tg": 178,
    "n": "AD",
    "locked": "2026-06-14"
   },
   {
    "gb": {
     "p": "Kane",
     "t": "ENG"
    },
    "as": {
     "p": "Lamine yamal",
     "t": "ESP"
    },
    "cards": "GER",
    "goals": "ESP",
    "mena": "MAR",
    "host": "USA",
    "tg": 225,
    "n": "Chris Ovenden",
    "locked": "2026-06-14"
   },
   {
    "gb": {
     "p": "Messi",
     "t": "ARG"
    },
    "as": {
     "p": "Messi",
     "t": "ARG"
    },
    "cards": "ESP",
    "goals": "BRA",
    "mena": "QAT",
    "host": "MEX",
    "tg": 222,
    "n": "Abdulaziz Alkhalifa",
    "locked": "2026-06-14"
   },
   {
    "gb": {
     "p": "Kai Havertz",
     "t": "GER"
    },
    "as": {
     "p": "Bruno Fernandes",
     "t": "POR"
    },
    "cards": "IRQ",
    "goals": "POR",
    "mena": "MAR",
    "host": "CAN",
    "tg": 230,
    "n": "Salem Athbi",
    "locked": "2026-06-14"
   },
   {
    "gb": {
     "p": "Kylian Mbappe",
     "t": "FRA"
    },
    "as": {
     "p": "Lamine Yamal",
     "t": "ESP"
    },
    "cards": "ENG",
    "goals": "ESP",
    "mena": "MAR",
    "host": "USA",
    "tg": 235,
    "n": "Rashed",
    "locked": "2026-06-15"
   },
   {
    "gb": {
     "p": "Yamal",
     "t": "ESP"
    },
    "as": {
     "p": "Valverde",
     "t": "URU"
    },
    "cards": "POR",
    "goals": "ESP",
    "mena": "MAR",
    "host": "USA",
    "tg": 153,
    "n": "Abdullah Mubarak",
    "locked": "2026-06-17"
   }
  ],
  "propsDeadline": "Open — TBC"
 },
 "propsLive": {
  "asOf": "2026-06-18",
  "matchesCounted": 24,
  "topScorers": [
   {
    "player": "Lionel Messi",
    "team": "ARG",
    "goals": 3,
    "pens": 0
   },
   {
    "player": "Harry Kane",
    "team": "ENG",
    "goals": 2,
    "pens": 1
   },
   {
    "player": "Kai Havertz",
    "team": "GER",
    "goals": 2,
    "pens": 1
   },
   {
    "player": "Elijah Just",
    "team": "NZL",
    "goals": 2,
    "pens": 0
   },
   {
    "player": "Erling Haaland",
    "team": "NOR",
    "goals": 2,
    "pens": 0
   },
   {
    "player": "Folarin Balogun",
    "team": "USA",
    "goals": 2,
    "pens": 0
   },
   {
    "player": "Kylian Mbappé",
    "team": "FRA",
    "goals": 2,
    "pens": 0
   },
   {
    "player": "Yasin Ayari",
    "team": "SWE",
    "goals": 2,
    "pens": 0
   },
   {
    "player": "Breel Embolo",
    "team": "SUI",
    "goals": 1,
    "pens": 1
   },
   {
    "player": "Marko Arnautović",
    "team": "AUT",
    "goals": 1,
    "pens": 1
   },
   {
    "player": "Abbosbek Fayzullaev",
    "team": "UZB",
    "goals": 1,
    "pens": 0
   },
   {
    "player": "Abdulelah Al-Amri",
    "team": "KSA",
    "goals": 1,
    "pens": 0
   },
   {
    "player": "Alexander Isak",
    "team": "SWE",
    "goals": 1,
    "pens": 0
   },
   {
    "player": "Ali Olwan",
    "team": "JOR",
    "goals": 1,
    "pens": 0
   },
   {
    "player": "Amad Diallo",
    "team": "CIV",
    "goals": 1,
    "pens": 0
   }
  ],
  "topAssists": [
   {
    "player": "Alexander Isak",
    "team": "SWE",
    "assists": 2,
    "goals": 1
   },
   {
    "player": "Deniz Undav",
    "team": "GER",
    "assists": 2,
    "goals": 1
   },
   {
    "player": "Chris Wood",
    "team": "NZL",
    "assists": 2,
    "goals": 0
   },
   {
    "player": "Joshua Kimmich",
    "team": "GER",
    "assists": 2,
    "goals": 0
   },
   {
    "player": "Ryan Gravenberch",
    "team": "NED",
    "assists": 2,
    "goals": 0
   },
   {
    "player": "Hwang In-beom",
    "team": "KOR",
    "assists": 1,
    "goals": 1
   },
   {
    "player": "Luis Díaz",
    "team": "COL",
    "assists": 1,
    "goals": 1
   },
   {
    "player": "Nathaniel Brown",
    "team": "GER",
    "assists": 1,
    "goals": 1
   },
   {
    "player": "Ramin Rezaeian",
    "team": "IRN",
    "assists": 1,
    "goals": 1
   },
   {
    "player": "Viktor Gyökeres",
    "team": "SWE",
    "assists": 1,
    "goals": 1
   },
   {
    "player": "Adrien Rabiot",
    "team": "FRA",
    "assists": 1,
    "goals": 0
   },
   {
    "player": "Alexander Freeman",
    "team": "USA",
    "assists": 1,
    "goals": 0
   },
   {
    "player": "Amir Al-Ammari",
    "team": "IRQ",
    "assists": 1,
    "goals": 0
   },
   {
    "player": "Arthur Masuaku",
    "team": "COD",
    "assists": 1,
    "goals": 0
   },
   {
    "player": "Brahim Díaz",
    "team": "MAR",
    "assists": 1,
    "goals": 0
   }
  ],
  "teamCards": [
   {
    "team": "RSA",
    "yellow": 2,
    "red": 2,
    "points": 8
   },
   {
    "team": "PAR",
    "yellow": 5,
    "red": 0,
    "points": 5
   },
   {
    "team": "MEX",
    "yellow": 1,
    "red": 1,
    "points": 4
   },
   {
    "team": "CIV",
    "yellow": 3,
    "red": 0,
    "points": 3
   },
   {
    "team": "NED",
    "yellow": 3,
    "red": 0,
    "points": 3
   },
   {
    "team": "SCO",
    "yellow": 3,
    "red": 0,
    "points": 3
   },
   {
    "team": "BIH",
    "yellow": 3,
    "red": 0,
    "points": 3
   },
   {
    "team": "POR",
    "yellow": 3,
    "red": 0,
    "points": 3
   },
   {
    "team": "BEL",
    "yellow": 2,
    "red": 0,
    "points": 2
   },
   {
    "team": "EGY",
    "yellow": 2,
    "red": 0,
    "points": 2
   },
   {
    "team": "BRA",
    "yellow": 2,
    "red": 0,
    "points": 2
   },
   {
    "team": "QAT",
    "yellow": 2,
    "red": 0,
    "points": 2
   }
  ],
  "teamGoals": [
   {
    "team": "GER",
    "goals": 7
   },
   {
    "team": "SWE",
    "goals": 5
   },
   {
    "team": "USA",
    "goals": 4
   },
   {
    "team": "NOR",
    "goals": 4
   },
   {
    "team": "ENG",
    "goals": 4
   },
   {
    "team": "FRA",
    "goals": 3
   },
   {
    "team": "ARG",
    "goals": 3
   },
   {
    "team": "AUT",
    "goals": 3
   },
   {
    "team": "COL",
    "goals": 3
   },
   {
    "team": "MEX",
    "goals": 2
   },
   {
    "team": "KOR",
    "goals": 2
   },
   {
    "team": "CZE",
    "goals": 2
   }
  ],
  "note": "Golden Boot from shot data; assists and cards from official match player stats; team goals from results. MENA and host props resolve on the bracket."
 }
};
if (typeof module !== 'undefined') module.exports = { WC_DATA };
